apache/fluss

fluss-server/src/main/java/com/alibaba/fluss/server/tablet/TabletServer.java
fix class name usage error in tablet server.
=> [hotfix] fix class name usage error in tablet server.

.github/PULL_REQUEST_TEMPLATE.md
Added pull request template.
this pr closes: #78
=> [hotfix] Added pull request template.

fluss-client/src/main/java/com/alibaba/fluss/client/lakehouse/LakeTableBucketAssigner.java
[hotfix][client] Change the class name assignment in exception message rendering.
N.A
N.A
N.A
=> [hotfix][client] Change the class name assignment in exception message rendering.

website/docs/install-deploy/deploying-distributed-cluster.md
Linked issue: [issue-112](https://github.com/alibaba/fluss/issues/112)
Add necessary software version descriptions to help users get started faster
Add document description, no need for ut
=> Add description of zookeeper version usage

fluss-client/src/main/java/com/alibaba/fluss/client/lookup/LookupClient.java
Rename lookupSenderTheadPool -> lookupSenderThreadPool
=> [hotfix] Fix typo

fluss-server/src/test/java/com/alibaba/fluss/server/replica/fetcher/ReplicaFetcherITCase.java
Linked issue: https://github.com/alibaba/fluss/issues/117
Fix unstable `testPutKvNeedAck()` in github CI.
=> [test] Fix unstable put kv test

fluss-common/src/main/java/com/alibaba/fluss/fs/local/LocalFileStatus.java, fluss-lakehouse/fluss-lakehouse-paimon/src/main/java/com/alibaba/fluss/lakehouse/paimon/sink/committer/PaimonStoreMultiCommitter.java
Not applicable.
Not applicable.
Not applicable.
Not applicable.
=> [fix]fix typo in project

website/docs/maintenance/tiered-storage/remote-storage.md
=> [doc] fix doc typo

fluss-client/src/main/java/com/alibaba/fluss/client/table/FlussTable.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/utils/PushdownUtils.java, fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/source/FlinkTableSourceBatchITCase.java
Linked issue: close [#165](https://github.com/alibaba/fluss/issues/165)
Add limit  scan on partition table to com.alibaba.fluss.connector.flink.source.FlinkTableSourceBatchITCase#testLimitLogTableScan
=> [connector] Fix leader not found when limit scan on partition table.

website/docs/maintenance/tiered-storage/overview.md
=> [docs] Fix typo in maintenance/tiered-storage/overview.md

website/docs/maintenance/tiered-storage/lakehouse-storage.md
=> [docs] Improve datalake storage doc

fluss-server/src/main/java/com/alibaba/fluss/server/kv/KvTablet.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/Replica.java
=> [hotfix] Fix the typo in comments

fluss-dist/src/main/assemblies/plugins.xml, fluss-dist/src/main/fluss-bin/bin/lakehouse.sh
Linked issue: close #178 
n/a
n/a
n/a
=> [dist][hotfix] Fix name of Hadoop filesystem plugin 

fluss-lakehouse/fluss-lakehouse-paimon/src/test/java/com/alibaba/fluss/lakehouse/paimon/source/FlussDatabaseSyncSourceITCase.java, fluss-lakehouse/fluss-lakehouse-paimon/src/test/java/com/alibaba/fluss/lakehouse/paimon/testutils/PaimonSyncTestBase.java, fluss-lakehouse/fluss-lakehouse-paimon/src/test/java/com/alibaba/fluss/lakehouse/paimon/testutils/TestingDatabaseSyncSink.java
Fix tiered storage database sync typo
=> [docs] Fix tiered storage database sync typo

pom.xml, website/docs/dev/ide-setup.md
=> [docs] Fix typo in ide-step-up doc

fluss-client/src/main/java/com/alibaba/fluss/client/lakehouse/paimon/PaimonBucketAssigner.java, fluss-client/src/main/java/com/alibaba/fluss/client/metrics/ScannerMetricGroup.java, fluss-client/src/main/java/com/alibaba/fluss/client/scanner/log/LogFetcher.java, fluss-common/src/main/java/com/alibaba/fluss/fs/FsPath.java, fluss-common/src/main/java/com/alibaba/fluss/fs/local/LocalFileSystem.java, fluss-common/src/main/java/com/alibaba/fluss/row/BinaryString.java, fluss-common/src/main/java/com/alibaba/fluss/utils/NetUtils.java, fluss-common/src/main/java/com/alibaba/fluss/utils/UnionIterator.java, fluss-common/src/test/java/com/alibaba/fluss/fs/SafetyNetCloseableRegistryTest.java, fluss-common/src/test/java/com/alibaba/fluss/record/LogTestBase.java, fluss-common/src/test/java/com/alibaba/fluss/row/TestInternalRowGenerator.java, fluss-common/src/test/java/com/alibaba/fluss/row/indexed/IndexedRowTest.java, fluss-common/src/test/java/com/alibaba/fluss/testutils/LogRecordBatchAssert.java, fluss-common/src/test/java/com/alibaba/fluss/utils/UnionIteratorTest.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/enumerator/initializer/BucketOffsetsRetrieverImpl.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/utils/FlinkConversions.java, fluss-filesystems/fluss-fs-hadoop/src/test/java/com/alibaba/fluss/fs/hdfs/HadoopDataInputStreamTest.java, fluss-lakehouse/fluss-lakehouse-paimon/src/main/java/com/alibaba/fluss/lakehouse/paimon/sink/committer/PaimonStoreMultiCommitter.java, fluss-metrics/fluss-metrics-jmx/src/test/java/com/alibaba/fluss/metrics/jmx/JMXServerTest.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/metrics/ClientMetricGroup.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/protocol/Errors.java, fluss-server/src/main/java/com/alibaba/fluss/server/kv/snapshot/RocksIncrementalSnapshot.java, fluss-server/src/main/java/com/alibaba/fluss/server/kv/wal/ArrowWalBuilder.java, fluss-server/src/main/java/com/alibaba/fluss/server/metrics/group/CoordinatorMetricGroup.java, fluss-server/src/main/java/com/alibaba/fluss/server/metrics/group/TabletServerMetricGroup.java, fluss-server/src/test/java/com/alibaba/fluss/server/kv/snapshot/TestCompletedSnapshotHandleStore.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/fetcher/ReplicaFetcherThreadTest.java
Fix some typo and format some code.
=> [Core] Fix some typo and format some code

website/docs/dev/ide-setup.md
"Save Actions Tool" is not maintained anymore and is not compatible with new versions of IntelliJ IDEA. See more: https://plugins.jetbrains.com/plugin/7642-save-actions
"Save Actions X" is a fork of "Save Actions Tool" and is compatible with recent IDEA versions. See more: https://plugins.jetbrains.com/plugin/22113-save-actions-x
=> [docs] Suggest to use "Save Actions X" instead of "Save Actions Tool"

fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/lakehouse/paimon/split/PaimonSnapshotAndFlussLogSplit.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/lakehouse/paimon/split/PaimonSnapshotSplit.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/split/HybridSnapshotLogSplit.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/split/LogSplit.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/split/SnapshotSplit.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/split/SourceSplitBase.java
=> [connector] Add toString to LogSplit.

website/deploy.sh
Linked to https://github.com/alibaba/fluss/issues/252
once new packages introduced,  executed `deploy.sh` throws as follows:
```
[cause]: Error: Docusaurus was unable to resolve the "@docusaurus/plugin-pwa" plugin. Make sure one of the following packages are installed:
- @docusaurus/plugin-pwa
- @docusaurus/docusaurus-plugin-plugin-pwa
```
we could add `install` stage to handle it.
run deploy.sh
=> [website] Add `install` stage to handle package changes

website/docs/maintenance/configuration.md, website/docs/maintenance/tiered-storage/lakehouse-storage.md
=> [docs] Fix typo in maintenance

website/docs/engine-flink/ddl.md
=> [docs] Fix typo in engine-flink/ddl.md

website/docs/engine-flink/reads.md
=> [docs] Fix typo in engine-flink/reads.md

website/docs/table-design/data-distribution/bucketing.md
=> [docs] Fix typo in table-design/data-distribution/bucketing.md

website/docs/maintenance/tiered-storage/overview.md
=> [docs] Fix typo in website/docs/maintenance/tiered-storage/overview.md

website/docs/table-design/overview.md
=> [docs] Fix typo in website/docs/table-design/overview.md

website/docs/streaming-lakehouse/overview.md
=> [docs] Fix typo in website/docs/streaming-lakehouse/overview.md

website/docs/maintenance/monitor-metrics.md, website/docs/quickstart/flink.md
as title, `coordinator-server`, `tablet-server`, `zookeeper` should be wrapped by fluss
=> docs: update comments in docker-compose.yml

fluss-connectors/fluss-connector-flink/pom.xml, fluss-lakehouse/fluss-lakehouse-paimon/pom.xml, fluss-lakehouse/fluss-lakehouse-paimon/src/main/java/com/alibaba/fluss/lakehouse/paimon/sink/NewTablesAddedPaimonListener.java, fluss-lakehouse/fluss-lakehouse-paimon/src/main/java/com/alibaba/fluss/lakehouse/paimon/sink/PaimonDataBaseSyncSinkBuilder.java, fluss-lakehouse/fluss-lakehouse-paimon/src/main/java/com/alibaba/fluss/lakehouse/paimon/sink/PaimonMultiTableSink.java, fluss-lakehouse/fluss-lakehouse-paimon/src/main/java/com/alibaba/fluss/lakehouse/paimon/sink/committer/PaimonStoreMultiCommitter.java, fluss-lakehouse/fluss-lakehouse-paimon/src/main/java/com/alibaba/fluss/lakehouse/paimon/sink/operator/PaimonMultiWriterOperator.java, fluss-lakehouse/fluss-lakehouse-paimon/src/main/java/com/alibaba/fluss/lakehouse/paimon/sink/operator/PaimonMultiWriterOperatorFactory.java, fluss-lakehouse/fluss-lakehouse-paimon/src/test/java/com/alibaba/fluss/lakehouse/paimon/sink/NewTableAddedPaimonListenerTest.java, pom.xml
Linked issue: close #374
Bump Paimon version from 0.8.2 to 1.0.1.
Backport:
- https://github.com/apache/paimon/commit/6fb8deebe8abfff9aa6296ea86a5dce905681f22
- https://github.com/apache/paimon/commit/406ab33d48c6c328732a74c38a27049e8d967045
- https://github.com/apache/paimon/commit/41df78a9b9d32c6264610a5ecdf7c4a078ff9812
- https://github.com/apache/paimon/commit/2a3410cdc5e6d876436f2b9cbfe09ce660171bf6
- https://github.com/apache/paimon/commit/f48cf172eb03659e8d095385abb309e18c6dcbb9
- https://github.com/apache/paimon/commit/6f4aa51b02f940838fc02da03a9a9cae6ac23e12
- https://github.com/apache/paimon/commit/4c6c557e6fd70e9ab9e5ebd4292f80340e5803ed
- https://github.com/apache/paimon/commit/c8f9b1860d37b7be25c97d5c842d5718d9cc9cd3
- …
=> [paimon] Bump Paimon version from 0.8.2 to 1.0.1

fluss-client/src/test/java/com/alibaba/fluss/client/table/FlussLakeTableITCase.java
Linked issue: close #299
This has been fixed in https://github.com/alibaba/fluss/pull/362. Just add a test case to cover this.
Added an IT case in `FlussLakeTableITCase`.
=> [client] Fix NullPointerException when deleting on a primary key table which enabled data lake

.github/PULL_REQUEST_TEMPLATE.md
To add pull request changes section to pull request template  to make contributor classify what changes in this pr.
=> [github] Add pull request changes section to pull request template

fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/ServerConnection.java
Linked issue: close #500
Not fail job when IOException is thrown when send to closed channel 
Wrap the IOException to NetworkException to retry send instead of failing job directly.
=> [netty] Wrap IOException to NetworkException to retry send to avoid making job fail directly

website/docs/engine-flink/ddl.md, website/docs/engine-flink/lookups.md, website/docs/table-design/table-types/pk-table/index.md
Linked issue: #493 
This pr is aims to add document about Prefix Lookup. The prefix lookup has been supported in pr: https://github.com/alibaba/fluss/pull/222
=> [docs] Add document about Prefix Lookup

website/docs/table-design/table-types/log-table.md
Linked issue: #492 
This pr is aims to add document about how to enable Arrow compression, different compress types, compress levels.
=> [docs] Add document for Arrow compression

fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/catalog/FlinkCatalog.java, fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/catalog/FlinkCatalogITCase.java, website/docs/engine-flink/ddl.md, website/docs/table-design/data-distribution/partitioning.md
Linked issue: #494 
We alreadt support `LIST/ADD/DROP PARTITIONS` in https://github.com/alibaba/fluss/pull/351
Add document for this feature in https://alibaba.github.io/fluss-docs/docs/engine-flink/ddl/
=> [docs] Add document for LIST/ADD/DROP PARTITION

website/docs/install-deploy/deploying-local-cluster.md, website/docs/maintenance/configuration.md
=> [docs] fix typo in docs

fluss-client/src/main/java/com/alibaba/fluss/client/utils/MetadataUtils.java
If timeout is short, it will cause the werid exception as described in #311 , this pr is aimed to increase timeout to 30s.
30s should be fine for most case..If not, the next following pr to introduce global configurable timeout and cache to polish it.
=> [hotfix] Increase timeout for update metadata request

website/docs/engine-flink/getting-started.md, website/docs/engine-flink/lookups.md
=> [hotfix][docs] improve some docs in getting-started.md and lookups.md

fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/ServerConnection.java
Linked issue: close #413
Init connectionMetricGroup before `bootstrap.connect` to avoid npe.
=> [rpc] Fix NullPointerException of ServerConnection

fluss-test-coverage/pom.xml
=> Use same version maven-deploy-plugin in Fluss.

fluss-client/src/main/java/com/alibaba/fluss/client/write/RecordAccumulator.java
=> [hotfix] Improve bucket ready check logic

fluss-dist/pom.xml
Linked issue: close #574 
mvn clean install -pl fluss-dist -am -DskipTests
=> Add all needed dependencies to fluss-dist.

.gitignore
[hotfix] ignore .vscode folder in .gitignore
A new .vscode folder will be created when using the vs code or cursor tool
=> [hotfix] ignore .vscode folder in .gitignore

README.md
Added descriptive alt text for the banner image to improve accessibility. Updated the development link to point to the correct GitHub page for IDE setup.
=> [README.md] Fixed link to Development instruction, cleaned up html

website/community/how-to-contribute/contribute-code.md, website/community/how-to-contribute/review-pull-requests.md
=> [docs] Add "Contribute Code" community documentation

fluss-client/src/main/java/com/alibaba/fluss/client/write/IdempotenceManager.java, fluss-client/src/main/java/com/alibaba/fluss/client/write/RecordAccumulator.java, fluss-client/src/test/java/com/alibaba/fluss/client/write/SenderTest.java
This is a hotfix pr to fix the wrong method name in `IdempotenceManager`.
=> [hotfix] Fix the wrong method name in IdempotenceManager

fluss-server/src/main/java/com/alibaba/fluss/server/replica/fetcher/RemoteLeaderEndpoint.java, fluss-server/src/main/java/com/alibaba/fluss/server/utils/RpcMessageUtils.java
Linked issue: close #602
Follower should pass partition id for list offset request
N/A, verify it in my env
=> [server] Follower should pass partition id for list offset request

website/community/dev/ide-setup.md
Linked issue: close #598
Changed docs according to linked issue
n/a
n/a
n/a
=> [Docs] Add instructions to fork repo to IDE setup page

website/community/dev/building.md, website/community/dev/ide-setup.md
Linked issue: close #578
- Added instruction for Git commit configuration to contributor guide (IDE setup)
- Fixed minor errors and inconsistencies in contributor guide
n/a
n/a
n/a
=> [Docs] Add instructions to set up git to contributor guide

website/docs/maintenance/observability/quickstart.md
Remove obsolete warning
n/a
n/a
n/a
n/a
=> [Docs] Remove obsolete warning in observability quickstart guide

fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorRequestBatch.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/ReplicaManager.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/fetcher/ReplicaFetcherManager.java, fluss-server/src/main/java/com/alibaba/fluss/server/tablet/TabletService.java, fluss-server/src/main/java/com/alibaba/fluss/server/utils/RpcMessageUtils.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/CoordinatorChannelManagerTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/tablet/TabletServiceITCase.java, fluss-server/src/test/java/com/alibaba/fluss/server/testutils/FlussClusterExtension.java
Linked issue: #636 
This pr is aims to change the `NotLeaderOrFollowerException` throw by `NotifyLeaderAndIsrRequest` from request level error to bucket level error. The reason is that for request level, `coordinatorServer` will ignore the result, but for bucket level, the request will be re-send for this bucket.
=> [server] Change the NotLeaderOrFollowerException throw by NotifyLeaderAndIsrRequest from request level error to bucket level error

website/docs/quickstart/flink.md
Add hint for users that catalog configurations are not persisted across SQL client sessions.
Added hint to quickstart guide
n/a
n/a
n/a
=> [Docs] Add note for Flink SQL catalog store persistence

fluss-flink/fluss-flink-1.18/pom.xml, fluss-flink/fluss-flink-1.19/pom.xml, fluss-flink/fluss-flink-1.20/pom.xml
When I build fluss-flink connector with main branch, I found the following exception:
```
[ERROR] Could not execute SQL statement. Reason:
org.apache.flink.table.api.ValidationException: Could not find any factory for identifier 'fluss' that implements 'org.apache.flink.table.factories.CatalogFactory' in the classpath.
Available factory identifiers are:
generic_in_memory
```
Then I found my jar doesn't contain the classes or `org.apache.flink.table.factories.Factory` file.
=> [hotfix] Include fluss-flink-common in fluss-flink jar

fluss-server/src/main/java/com/alibaba/fluss/server/replica/ReplicaManager.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/fetcher/InitialFetchStatus.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/fetcher/LeaderEndpoint.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/fetcher/RemoteLeaderEndpoint.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/fetcher/ReplicaFetcherManager.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/fetcher/ReplicaFetcherThread.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/fetcher/ReplicaFetcherManagerTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/fetcher/ReplicaFetcherThreadTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/fetcher/TestingLeaderEndpoint.java, fluss-server/src/test/java/com/alibaba/fluss/server/tablet/TabletServiceITCase.java
Linked issue: close #633 
Now, the tablet server gateway to fetch log from leader is static, which will cause if the leader change/failover,  it will still fetch log from old ip address.
Assuming the case:
- server 0 is follower, server 1 is leader.  Coordinator server down.
- server 1 down
- server 1 up and ip is changed, but the server 0 will stil try to fetch from old ip address.
`ReplicaFetcherThread` use dynamic tablet server gateway to fetch log from leader, which will got latest server node of the tablet server. 
Exsting tests has covered it.
=> [server] Use dynamic tablet server gateway for fetching log from leader 

fluss-client/src/test/java/com/alibaba/fluss/client/admin/FlussAdminITCase.java, fluss-server/src/main/java/com/alibaba/fluss/server/kv/snapshot/CompletedSnapshotJsonSerde.java, fluss-server/src/main/java/com/alibaba/fluss/server/kv/snapshot/KvFileHandle.java, fluss-server/src/main/java/com/alibaba/fluss/server/kv/snapshot/KvSnapshotDataDownloader.java, fluss-server/src/main/java/com/alibaba/fluss/server/kv/snapshot/SharedKvFileRegistryKey.java, fluss-server/src/main/java/com/alibaba/fluss/server/kv/snapshot/SnapshotLocation.java, fluss-server/src/main/java/com/alibaba/fluss/server/utils/RpcMessageUtils.java, fluss-server/src/test/java/com/alibaba/fluss/server/kv/snapshot/CompletedSnapshotJsonSerdeTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/kv/snapshot/CompletedSnapshotTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/kv/snapshot/KvSnapshotDataDownloaderTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/kv/snapshot/KvSnapshotDataUploaderTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/kv/snapshot/SharedKvFileRegistryTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/kv/snapshot/SnapshotsCleanerTest.java
=> [server] Replace FsPath with String in KvFileHandle

fluss-common/src/main/java/com/alibaba/fluss/compression/FlussLZ4BlockOutputStream.java, fluss-kafka/src/main/java/com/alibaba/fluss/kafka/KafkaCommandDecoder.java, fluss-kafka/src/test/java/com/alibaba/fluss/kafka/KafkaConfigsTest.java, fluss-kafka/src/test/java/com/alibaba/fluss/kafka/KafkaRequestHandlerTest.java, fluss-kafka/src/test/java/com/alibaba/fluss/kafka/TestingTabletGatewayService.java, tools/maven/checkstyle.xml
=> [hotfix] Add MissingJavadocType checkstyle

fluss-server/src/main/java/com/alibaba/fluss/server/log/LogLoader.java, fluss-server/src/main/java/com/alibaba/fluss/server/log/LogManager.java, fluss-server/src/main/java/com/alibaba/fluss/server/log/LogTablet.java, fluss-server/src/test/java/com/alibaba/fluss/server/kv/KvTabletTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/log/LogManagerTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/log/LogTabletTest.java
Linked issue: #671 
Add cleanShutdown mark to indicate whether the LogManager's previous exit was a clean shutdown or an abnormal exit. This pr is aims to fix the error show in #671
=> [server] Add cleanShutdown mark to indicate whether the LogManager's previous exit was a clean shutdown or an abnormal exit

fluss-server/src/test/java/com/alibaba/fluss/server/replica/AdjustIsrITCase.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/fetcher/ReplicaFetcherITCase.java, fluss-server/src/test/java/com/alibaba/fluss/server/testutils/FlussClusterExtension.java
To fix the unstable testFlushForPutKvNeedAck test.
Sleep 2s before https://github.com/alibaba/fluss/pull/682/files#diff-c7b360fdb4b449de5f6d56dbcc886c003962fe1340b925707653fcd7ec57a1aaL274 , the test will fail. 
Not kill the tabletserver, just stop the follower so that it'll cost a period of time to shrink isr.
=> [hotfix] Fix unstable testFlushForPutKvNeedAck test

fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/server/ServerChannelInitializer.java
=> [server] Use ChannelId#hashCode() in ServerChannelInitializer

fluss-common/src/main/java/com/alibaba/fluss/cluster/Endpoint.java, fluss-common/src/test/java/com/alibaba/fluss/cluster/EndpointTest.java
Linked issue: close #714
Adapted `com/alibaba/fluss/cluster/Endpoint.java` according to issue
Adapted existing test case.
n/a
n/a
=> Throw exception when `[coordinator|tablet-server].host` and `bind.listeners` are both set

fluss-rpc/src/main/java/com/alibaba/fluss/rpc/gateway/TabletServerGateway.java
TabletServerGateway have a comment error，it should be `tablet server`。
=> [hotfix] Fix tablet gateway comment error.

website/docs/maintenance/observability/monitor-metrics.md
This pr is a hotfix pr to fix the issue of unaligned table content in monitor-metrics.md. Currently, there are two tables have the unaligned content problem:
=> [hotfix] Fix the issue of unaligned table content in monitor-metrics.md

fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/sink/FlinkTableSinkITCase.java
=> [build] ParameterizedTest in FlinkTableSinkITCase will hang to timeout when run CI on Github

fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/server/NettyServerHandler.java, fluss-rpc/src/test/java/com/alibaba/fluss/rpc/netty/server/NettyServerHandlerTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/tablet/TabletServiceITCase.java
Revert #681 (Response return in order) to ensure performance
=> Revert #681 (Response return in order) to ensure performance

fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/ServerConnection.java
I saw the following exception in latest code:
```
com.alibaba.fluss.shaded.netty4.io.netty.util.concurrent.DefaultPromise [] - An exception was thrown by com.alibaba.fluss.rpc.netty.client.ServerConnection$$Lambda$1148/205810839.operationComplete()
java.lang.NullPointerException: null
at com.alibaba.fluss.rpc.netty.client.ServerConnection.doSend(ServerConnection.java:331) ~[blob_p-7e3af4e07fc858814e8ea7895fbf4852ac7e3d55-c54dd5d95c51cd350912cd4d8f2bde1d:0.6-ali-2-SNAPSHOT]
at 
```
The pr is to fix it.
in #564 , this has been fixed. But in #577 , the statement order changes which will bring the npe.
=> [hotfix] Fix npe in ServerConnection

fluss-common/src/main/java/com/alibaba/fluss/metrics/MetricNames.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/Replica.java
=> [server] Introduce underReplicatedBuckets metrics

fluss-server/src/test/java/com/alibaba/fluss/server/log/remote/CommitRemoteLogManifestITCase.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/AdjustIsrITCase.java
=> [server] Add ITCase for deleting local log if replica is out of sync

fluss-common/src/main/java/com/alibaba/fluss/metrics/MetricNames.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorEventProcessor.java
=> [server] Introduce replicasToDeleteCount metrics

fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/server/RequestsMetrics.java
=> [rpc] Report get metadata metrics

fluss-server/src/test/java/com/alibaba/fluss/server/tablet/TabletServerFailOverITCase.java
=> [server] Add IT for kill follower & leader servers

fluss-server/src/test/java/com/alibaba/fluss/server/log/remote/RemoteLogITCase.java
Linked issue: close #137 
Add create, download, metadata tests in RemoteLogITCase
Already added tests
N/A
N/A
=> [server][issue-137] feat: add more tests in RemoteLogITCase

website/docs/maintenance/observability/monitor-metrics.md
=> Add "underReplicated", "request_metadata", "replicasToDeleteCount" metrics to documentation

fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorContext.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/statemachine/ReplicaStateMachine.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/statemachine/TableBucketStateMachine.java
=> Add DEBUG logging for bucket/replica state machine changing

fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/source/FlinkTableSource.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/source/FlussSourceBuilder.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/source/enumerator/initializer/OffsetsInitializer.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlussSourceBuilderTest.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/enumerator/FlinkSourceEnumeratorTest.java, fluss-lakehouse/fluss-lakehouse-paimon/src/test/java/com/alibaba/fluss/lakehouse/paimon/flink/LakeTableEnumeratorTest.java
=> Rename OffsetsInitializer#initial() to full()

fluss-common/src/main/java/com/alibaba/fluss/row/TimestampNtz.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/source/deserializer/JsonStringDeserializationSchema.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/utils/FlussRowToJsonConverters.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/utils/TimeFormats.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/utils/TimestampFormat.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/deserializer/FlussDeserializationSchemaTest.java
Linked issue: close #678 
Add `FlussRowToJsonConverters`
`FlussDeserializationSchemaTest.testJsonStringDeserialize`
=> [DataStream] Introduce converter for fluss row to json

fluss-common/src/main/java/com/alibaba/fluss/row/GenericRow.java, fluss-common/src/test/java/com/alibaba/fluss/row/GenericRowTest.java, fluss-common/src/test/java/com/alibaba/fluss/row/ProjectedRowTest.java, fluss-test-coverage/pom.xml
Linked issue: #855 
This pr is aims to increase code coverage for class `GenericRow`. To see the detail code coverage ratio, you can use run with Coverage in idea:
The result will be shown after running:
=> [test] Increase code coverage for class GenericRow

fluss-server/src/test/java/com/alibaba/fluss/server/replica/CommitLakeTableSnapshotITCase.java
Linked issue: close #866
We should wait replica ready before performing `produceLog` request.
=> [test] Fix unstable test CommitLakeTableSnapshotITCase#testCommitDataLakeData

.github/workflows/ci.yaml
=> [ci] Upload jacoco report when running main branch

fluss-server/src/main/java/com/alibaba/fluss/server/log/remote/RemoteLogManager.java, fluss-server/src/test/java/com/alibaba/fluss/server/log/remote/CommitRemoteLogManifestITCase.java, fluss-server/src/test/java/com/alibaba/fluss/server/testutils/FlussClusterExtension.java
Linked issue: close #870 
Introduce jitter for upload log segment
=> [server] Introduce jitter for upload remote log

fluss-common/src/main/java/com/alibaba/fluss/config/FlussConfigUtils.java, fluss-common/src/test/java/com/alibaba/fluss/config/FlussConfigUtilsTest.java, fluss-test-coverage/pom.xml
=> Increase code coverage for class FlussConfigUtils

fluss-common/src/main/java/com/alibaba/fluss/utils/crc/Crc32C.java, fluss-common/src/test/java/com/alibaba/fluss/utils/crc/Crc32CTest.java, fluss-test-coverage/pom.xml
=> Increase code coverage for class Crc32C

fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/reader/RecordAndPosTest.java, fluss-test-coverage/pom.xml
=> Increase code coverage for class RecordAndPos

fluss-common/src/test/java/com/alibaba/fluss/cluster/ServerNodeTest.java, fluss-test-coverage/pom.xml
=> Increase code coverage for class ServerNode

fluss-client/src/main/java/com/alibaba/fluss/client/table/scanner/log/LogFetchBuffer.java, fluss-client/src/main/java/com/alibaba/fluss/client/table/scanner/log/LogScannerImpl.java, fluss-client/src/test/java/com/alibaba/fluss/client/table/scanner/log/LogFetchBufferTest.java, fluss-common/src/main/java/com/alibaba/fluss/exception/WakeupException.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/catalog/FlinkCatalogITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/metrics/FlinkMetricsITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/security/acl/FlinkAuthorizationITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/sink/FlinkTableSinkITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlinkTableSourceBatchITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlinkTableSourceITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlussSourceITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/testutils/FlinkTestBase.java, fluss-server/src/main/java/com/alibaba/fluss/server/authorizer/DefaultAuthorizer.java, fluss-server/src/main/java/com/alibaba/fluss/server/authorizer/ZkNodeChangeNotificationWatcher.java, fluss-server/src/main/java/com/alibaba/fluss/server/tablet/TabletService.java, fluss-server/src/main/java/com/alibaba/fluss/server/zk/ZooKeeperClient.java, fluss-server/src/test/java/com/alibaba/fluss/server/testutils/FlussClusterExtension.java
Linked issue: close #933
1. The first commit fix a lot of `LogFetchCollector` log in maven output, because the `LogScanner#wakeup()` didn't interrupt `LogScanner#poll()`
2. The second commit follows the suggested way of [MiniClusterExtension](https://github.com/apache/flink/blob/release-1.20.1/flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/test/junit5/MiniClusterExtension.java#L59) to initialize `StreamExecutionEnvironment` in each test method instead of being shared in the test class.
=> Fix Flink CI timeout

fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/PaimonLakeCatalog.java, website/docs/streaming-lakehouse/integrate-data-lakes/paimon.md
Fluss and Paimon data type mapping document adds binary and bytes data types
=> [doc] Fluss and Paimon data type mapping document adds binary and bytes data types

fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/sink/writer/UpsertSinkWriter.java
=> [doc]Removed duplicated java doc in UpsertSinkWriter

fluss-common/src/main/java/com/alibaba/fluss/security/auth/ServerAuthenticator.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/server/NettyServerHandler.java, fluss-rpc/src/test/java/com/alibaba/fluss/rpc/netty/authenticate/AuthenticationTest.java, fluss-rpc/src/test/java/com/alibaba/fluss/rpc/netty/authenticate/MutualAuthenticationPlugin.java
=> [server] Add keep alive method for ServerAuthenticator for each rpc invocation.

fluss-filesystems/fluss-fs-oss/src/main/java/com/alibaba/fluss/fs/oss/OSSFileSystemPlugin.java, fluss-filesystems/fluss-fs-oss/src/test/java/com/alibaba/fluss/fs/oss/OSSWithCredentialsProviderFileSystemBehaviorITCase.java, website/docs/maintenance/filesystems/oss.md
…
Linked issue: close #936 
To allow OssFileSystem to configure credential provider
if credential provider is set, not to always use `DynamicTemporaryOssCredentialsProvider`, use user's configured provider
`OSSWithCredentialsProviderFileSystemBehaviorITCase`
=> [filesystem/oss] OssFileSystem should allow to configure credential provider

fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/sink/FlinkSink.java
=> [hotfix] Remove duplicate comments

fluss-client/src/main/java/com/alibaba/fluss/client/write/ArrowLogWriteBatch.java, fluss-client/src/main/java/com/alibaba/fluss/client/write/IdempotenceManager.java, fluss-client/src/main/java/com/alibaba/fluss/client/write/IncompleteBatches.java, fluss-client/src/main/java/com/alibaba/fluss/client/write/IndexedLogWriteBatch.java, fluss-client/src/main/java/com/alibaba/fluss/client/write/KvWriteBatch.java, fluss-client/src/main/java/com/alibaba/fluss/client/write/RecordAccumulator.java, fluss-client/src/main/java/com/alibaba/fluss/client/write/Sender.java, fluss-client/src/main/java/com/alibaba/fluss/client/write/WriteBatch.java, fluss-client/src/test/java/com/alibaba/fluss/client/security/acl/FlussAuthorizationITCase.java, fluss-client/src/test/java/com/alibaba/fluss/client/write/ArrowLogWriteBatchTest.java, fluss-client/src/test/java/com/alibaba/fluss/client/write/IndexedLogWriteBatchTest.java, fluss-client/src/test/java/com/alibaba/fluss/client/write/KvWriteBatchTest.java, fluss-common/src/main/java/com/alibaba/fluss/record/KvRecordBatchBuilder.java, fluss-common/src/main/java/com/alibaba/fluss/record/MemoryLogRecordsArrowBuilder.java, fluss-common/src/main/java/com/alibaba/fluss/record/MemoryLogRecordsIndexedBuilder.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/security/acl/FlinkAuthorizationITCase.java, fluss-rpc/src/main/proto/FlussApi.proto, fluss-server/src/main/java/com/alibaba/fluss/server/tablet/TabletService.java
Linked issue: close #931  and #756 
Currently, if Sender try to send InitWriter request and failed with AuthorizationException, it will not raise the exception to record callbacks, which will cause the flink client keep retrying. In this case, we need to trigger abortBatch() to let these writeBatches in accumulator to abort and raise exception to record callbacks. See comments in https://github.com/alibaba/fluss/pull/850
=> [client] Sender trigger to abort all writeBatches if InitWriter failed with AuthorizationException

fluss-client/src/main/java/com/alibaba/fluss/client/utils/MetadataUtils.java
`	public String getRack() {
if (!hasRack()) {
throw new IllegalStateException("Field 'rack' is not set");
}
return rack;
}`
getRack() will throw Exception when there is no rack.
So before call getRack() we have to judge if hasRack()
=> [hotfix] Fix a bug which throw exception when no rack was configured

fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorEventProcessor.java
Linked issue: close #988 
This pr is aims to fix the unstable test `RemoveOfflineReplicaFromIsrITCase.testRemoveOfflineReplicaFromIsr`. The reason why this test become unstable is that in pr #757, we change the way the `updateMetadata request` sent when tabletServer offline.  In `CoordinatorEventProcessor#processDeadTabletServer`, we need send a separate  updateMetadata request to update aliveTabletServer set, the purpose of this approach is to prevent the scenario where `NotifyLeaderAndIsrRequest` gets sent before `UpdateMetadataRequest`, which could cause the leader to incorrectly adjust isr.
=> [test] Fix unstable test RemoveOfflineReplicaFromIsrITCase.testRemoveOfflineReplicaFromIsr

fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/tiering/source/TestingLakeTieringFactory.java
Fix compile error in:
https://github.com/alibaba/fluss/actions/runs/15481927297/job/43589199477
=> [hotfix] Fix TestingLakeTieringFactory compile error

fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/MetadataManager.java
Try catch `KeeperException.NodeExistsException nodeExistsException`, and not throw exception when set ignoreIfExists to true
Hard to mock this corner case, but verify in our pre env
=> [hotfix] Not to throw KeeperException$NodeExistsException for partition node if set ignoreIfExists to true

fluss-common/src/test/java/com/alibaba/fluss/row/BinaryStringTest.java, fluss-test-coverage/pom.xml
Linked issue: close #885 
Improve test coverage on BinarySection
=> [row] improve test converage on BinarySection

README.md
Linked issue: n/a
Adjust logo in README based on user's mode setting (light mode/dark mode).
n/a
n/a
n/a
=> Adjust logo based on light/dark mode

website/docs/engine-flink/ddl.md, website/docs/table-design/data-distribution/partitioning.md
=> Add documentation for multi-fields partition

fluss-client/src/main/java/com/alibaba/fluss/client/admin/Admin.java, fluss-client/src/main/java/com/alibaba/fluss/client/admin/FlussAdmin.java, fluss-client/src/main/java/com/alibaba/fluss/client/utils/ClientRpcMessageUtils.java, fluss-client/src/test/java/com/alibaba/fluss/client/admin/ClientToServerITCaseBase.java, fluss-client/src/test/java/com/alibaba/fluss/client/admin/FlussAdminITCase.java, fluss-common/src/main/java/com/alibaba/fluss/metadata/ResolvedPartitionSpec.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/catalog/FlinkCatalog.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/catalog/FlinkCatalogITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/catalog/FlinkCatalogTest.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/util/CommonRpcMessageUtils.java, fluss-rpc/src/main/proto/FlussApi.proto, fluss-server/src/main/java/com/alibaba/fluss/server/RpcServiceBase.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/MetadataManager.java, fluss-server/src/main/java/com/alibaba/fluss/server/utils/ServerRpcMessageUtils.java, fluss-server/src/main/java/com/alibaba/fluss/server/zk/ZooKeeperClient.java
=> [server] Support list partititions by partition spec

fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/server/FlussRequest.java
=> [server] Safely release buffer in FlussRequest.

website/docs/engine-flink/reads.md
Linked issue: close #1078 
This pr is aims to add documentation for column pruning and partition pruning
=> [docs] Add documentation for column pruning and partition pruning

fluss-common/src/main/java/com/alibaba/fluss/config/ConfigOptions.java, fluss-common/src/main/java/com/alibaba/fluss/security/auth/sasl/authenticator/SaslClientAuthenticator.java, fluss-rpc/src/test/java/com/alibaba/fluss/rpc/netty/authenticate/SaslAuthenticationITCase.java
=> [client] Simply username and password config for client.

website/community/welcome.md
Added calender invite for fluss community call and modified slack message more community friendly
None
None
Changes the Community Docs
=> [website] Change calender invite & slack invite words for more community vibe

website/community/how-to-contribute/contribute-docs.md, website/docs/install-deploy/deploying-with-docker.md, website/docs/maintenance/observability/quickstart.md, website/docs/quickstart/flink.md, website/fluss-versions.json, website/src/plugins/remark-version-replace/index.js
=> [docs] Introduce `$FLUSS_DOCKER_VERSION$` expression to reference docker image version

fluss-client/src/test/java/com/alibaba/fluss/client/security/acl/FlussAuthorizationITCase.java, fluss-server/src/main/java/com/alibaba/fluss/server/RpcServiceBase.java, fluss-server/src/main/java/com/alibaba/fluss/server/authorizer/DefaultAuthorizer.java, fluss-server/src/main/java/com/alibaba/fluss/server/tablet/TabletServer.java, fluss-server/src/test/java/com/alibaba/fluss/server/testutils/FlussClusterExtension.java
cherry-pick #1102 to release-0.7
=> [test] Fix unstable test cases in FlussAuthorizationITCase

fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/LakeTieringJobBuilder.java
Set default name for flink tiering service job
=> [minor][lake] Set default name for flink tiering service job 

fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/LakeTieringJobBuilder.java, fluss-flink/fluss-flink-tiering/src/main/java/com/alibaba/fluss/flink/tiering/FlussLakeTieringEntrypoint.java
Set default name for flink tiering service job
=> [minor][lake] Set default name for flink tiering service job

fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/FlussRecordAsPaimonRow.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/RecordWriter.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/append/AppendOnlyWriter.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/mergetree/MergeTreeWriter.java, fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/tiering/FlussRecordAsPaimonRowTest.java
=> [lake/paimon] Fix than tiering service for paimon missed timestampNtz support

website/docs/streaming-lakehouse/integrate-data-lakes/paimon.md
Linked issue: close #448
[lake/docs] Update Paimon docs in lakehouse section
=>  [lake/docs] Update paimon integration docs in lakehouse section

fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/lakehouse/paimon/reader/PaimonSnapshotAndLogSplitScanner.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/lakehouse/paimon/reader/ScanRecordWrapper.java, fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/flink/FlinkUnionReadPrimaryKeyTableITCase.java, fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/testutils/FlinkPaimonTieringTestBase.java
=> [lake/paimon] Fix union read timestamp type issue (#1128)

fluss-client/src/main/java/com/alibaba/fluss/client/table/scanner/log/LogFetcher.java
=> [hotfix] Add isClosed protect for LogFetcher#handleFetchLogException to avoid throw exception if channel close

fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlinkTableSourceITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlussSourceITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/reader/FlinkSourceReaderTest.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/utils/FlinkTestBase.java, fluss-server/src/main/java/com/alibaba/fluss/server/tablet/TabletServer.java, fluss-server/src/test/java/com/alibaba/fluss/server/testutils/FlussClusterExtension.java
=> [test] Expose Clock to FlussClusterExtension.

fluss-flink/fluss-flink-1.18/pom.xml, fluss-flink/fluss-flink-1.19/pom.xml, fluss-flink/fluss-flink-1.20/pom.xml, pom.xml
=> [test/flink] Se forkCount=1 for versioned flink e2e tests

website/docs/engine-flink/getting-started.md
=> [hotfix] fix typos in getting-started.md

website/docs/apis/java-client.md
=> [hotfix] Fix the missing brackets in java-client.md

website/docs/apis/java-client.md
Code structure issues
https://alibaba.github.io/fluss-docs/docs/apis/java-client/
there are two mistakes，#1225 only fixed one
=> [doc]Code structure issues

website/community/welcome.md
Linked issue: close #1255 
Add links to subscribe and unsubscribe to the dev and users mailing lists for the community
None
None
None
=> [website] Add apache mailing list info for community

fluss-dist/src/main/resources/server.yaml
fix typo in server.yaml
Fix typo in server.yaml 
THe -> The
=> [hotfix] Fix typo in server.yaml

fluss-client/src/main/java/com/alibaba/fluss/client/token/SecurityTokenReceiverRepository.java, fluss-common/src/main/java/com/alibaba/fluss/fs/FileSystem.java, fluss-common/src/main/java/com/alibaba/fluss/lake/lakestorage/LakeStoragePluginSetUp.java, fluss-common/src/main/java/com/alibaba/fluss/security/auth/AuthenticationFactory.java, fluss-common/src/main/java/com/alibaba/fluss/security/auth/sasl/jaas/DefaultLogin.java, fluss-common/src/test/java/com/alibaba/fluss/security/auth/AuthenticationFactoryTest.java, fluss-common/src/test/java/com/alibaba/fluss/utils/ParentResourceBlockingClassLoader.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/catalog/FlinkCatalogITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/security/acl/FlinkAuthorizationITCase.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/server/NettyServer.java, fluss-server/src/main/java/com/alibaba/fluss/server/authorizer/AuthorizerLoader.java
=> [client] Fluss client shouldn't load plugin by thread context classloader.

website/docusaurus.config.ts, website/learn/talks.md, website/learn/videos.md
Linked issue: close #1204 
Added a new .md file for learn & videos, also modified the docusaurus.config.ts to include 2 new pages
None
None
None
=> [website] Learn page for talks & videos draft version

fluss-common/src/main/java/com/alibaba/fluss/metrics/MetricNames.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/event/CoordinatorEventManager.java, website/docs/maintenance/observability/monitor-metrics.md
=> [Docs] Coordinator event metrics

website/src/pages/roadmap.md
Linked issue: #1203
Update roadmap to reflect v0.8 features, timeline, and latest project additions.
- Added "Fluss Server" section for HA, cluster operations, and optimizations
- Added Streaming Lakehouse production-ready features and Lance support
- Added Spark connector, Python client, and Helm charts sections
- Updated Java version from 17 to 11
- Reorganized Flink integration with system tables support
- Added GitHub issue references and milestone board link
None
None
Yes. Enhanced roadmap with v0.8 features, timeline, and improved organization for better project visibility.
=> [website] update roadmap to account latest requirements

fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/event/CoordinatorEventManager.java
=> [debug] Add coordinator event debug log

fluss-server/src/main/java/com/alibaba/fluss/server/ServerBase.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorServer.java, fluss-server/src/main/java/com/alibaba/fluss/server/tablet/TabletServer.java
=> [coordinator] add retry for Coordinator Server when register to zk

fluss-common/src/main/java/com/alibaba/fluss/lake/committer/LakeCommitter.java, fluss-common/src/main/java/com/alibaba/fluss/lake/writer/LakeTieringFactory.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/LakeTieringJobBuilder.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/committer/TieringCommitOperator.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/tiering/TestingLakeTieringFactory.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeCommitter.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeTieringFactory.java, fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/tiering/PaimonTieringTest.java, website/blog/2025-07-01-tiering-service.md
fix error word `commitable` to `committable`.
=> [hotfix] fix error word commitable to committable.

website/docs/table-design/table-types/pk-table/index.md
Modify the table format in the pk-table document
https://fluss.apache.org/docs/table-design/table-types/pk-table/
=> [doc]Modify the table format in the pk-table document

README.md, website/community/welcome.md
Linked issue: close #1315
Update the latest slack invitation link for workspace
Changed the invitation link in welcome.md and readme.md
None
None
None
=> [docs] update apache fluss slack link

fluss-client/src/main/java/com/alibaba/fluss/client/admin/FlussAdmin.java, fluss-client/src/test/java/com/alibaba/fluss/client/admin/FlussAdminITCase.java, fluss-client/src/test/java/com/alibaba/fluss/client/security/acl/FlussAuthorizationITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/procedure/FlinkProcedureITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/security/acl/FlinkAuthorizationITCase.java, fluss-server/src/main/java/com/alibaba/fluss/server/ServerBase.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorServer.java, fluss-server/src/test/java/com/alibaba/fluss/server/testutils/FlussClusterExtension.java
=> Fluss admin use tablet server for read only operation to reduce the cost of coordinator.

fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonCommittableSerializer.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonWriteResultSerializer.java
=> [bug fix] decouple the serializer version of PaimonWriteResult and PaimonCommittable

website/src/css/custom.css
=> [docs] fix: code block render issue

website/docs/maintenance/tiered-storage/lakehouse-storage.md
Although it's just a demo, but still fix it to avoid misleading.
=> [docs] Fix warehouse path of paimon inconsistent in lakehouse-storage page

fluss-common/src/main/java/com/alibaba/fluss/utils/concurrent/Scheduler.java
=> [typo] Fix typo in Scheduler.java

fluss-client/src/main/java/com/alibaba/fluss/client/lookup/Lookuper.java, website/docs/apis/java-client.md
1. `Lookuper` interface doc 
2. java-client doc
=> [doc] fix some docs of prefix lookup api

website/community/welcome.md
Add brief info around video recording and summary/note taking setup
Modified welcome.md to add community related info
None
None
None
=> [docs] Add info around community resources including notes and recording

fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/committer/TieringCommitOperator.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/tiering/committer/TieringCommitOperatorTest.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeCommitter.java
fix typos `commited` -> `committed`
=> [typo] fix typos commited -> committed

fluss-server/src/main/java/com/alibaba/fluss/server/utils/TableAssignmentUtils.java
Currently in Fluss, it is possible to successfully create a table with zero buckets. In fact, this should be invalid; if a user attempts to create a table or partition with zero buckets, an error should be returned immediately instead of allowing the creation to succeed and only reporting an error during read or write operations.
=> [server] Prohibit the creation of TableAssignment with zero buckets

website/blog/2025-07-23-hands-on-fluss-lakehouse.md
=> Fix typo in "From Stream to Lake" blog

fluss-server/src/main/java/com/alibaba/fluss/server/metrics/ServerMetricUtils.java, fluss-server/src/main/java/com/alibaba/fluss/server/metrics/group/TabletServerMetricGroup.java, fluss-server/src/main/java/com/alibaba/fluss/server/tablet/TabletServer.java, fluss-server/src/test/java/com/alibaba/fluss/server/metrics/group/TestingMetricGroups.java
=> [server] Add rack label for tablet server metrics

website/docs/maintenance/filesystems/hdfs.md
=> [docs] Add a section for hadoop related configuration

fluss-lake/fluss-lake-iceberg/src/main/java/com/alibaba/fluss/lake/iceberg/IcebergLakeCatalog.java, fluss-lake/fluss-lake-iceberg/src/test/java/com/alibaba/fluss/lake/iceberg/IcebergLakeCatalogTest.java
Linked issue: close https://github.com/apache/fluss/issues/1329
- support log table in IcebergLakeCatalog
In progress
=> [lake/iceberg] Support Log Table in IcebergLakeCatalog

fluss-common/src/test/java/com/alibaba/fluss/lake/lakestorage/LakeStorageTest.java, fluss-lake/fluss-lake-iceberg/src/main/java/com/alibaba/fluss/lake/iceberg/FlussDataTypeToIcebergDataType.java, fluss-lake/fluss-lake-iceberg/src/test/java/com/alibaba/fluss/lake/iceberg/IcebergLakeCatalogTest.java, fluss-lake/fluss-lake-lance/src/main/resources/META-INF/services/com.alibaba.fluss.lake.lakestorage.LakeStoragePlugin, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/utils/FlussToPaimonPredicateConverter.java, fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/source/PaimonLakeSourceTest.java, fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/utils/FlussToPaimonPredicateConverterTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/fetcher/RemoteLeaderEndpointTest.java, website/docs/quickstart/security.md
=> [hotfix] Modify file header to licensed to Apache Software Foundation

.github/workflows/ci-template.yaml, .github/workflows/ci.yaml, .github/workflows/stage.sh, fluss-flink/fluss-flink-1.18/src/main/java/com/alibaba/fluss/flink/adapter/CatalogTableAdapter.java, fluss-flink/fluss-flink-1.18/src/main/java/com/alibaba/fluss/flink/adapter/SingleThreadFetcherManagerAdapter.java, fluss-flink/fluss-flink-1.18/src/main/java/com/alibaba/fluss/flink/adapter/SingleThreadMultiplexSourceReaderBaseAdapter.java, fluss-flink/fluss-flink-1.19/src/main/java/com/alibaba/fluss/flink/adapter/CatalogTableAdapter.java, fluss-flink/fluss-flink-2.1/pom.xml, fluss-flink/fluss-flink-2.1/src/main/java/org/apache/flink/api/connector/sink2/Sink.java, fluss-flink/fluss-flink-2.1/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, fluss-flink/fluss-flink-2.1/src/test/java/com/alibaba/fluss/flink/catalog/Flink21CatalogITCase.java, fluss-flink/fluss-flink-2.1/src/test/java/com/alibaba/fluss/flink/metrics/Flink21MetricsITCase.java, fluss-flink/fluss-flink-2.1/src/test/java/com/alibaba/fluss/flink/procedure/Flink21ProcedureITCase.java, fluss-flink/fluss-flink-2.1/src/test/java/com/alibaba/fluss/flink/security/acl/Flink21AuthorizationITCase.java, fluss-flink/fluss-flink-2.1/src/test/java/com/alibaba/fluss/flink/sink/Flink21TableSinkITCase.java, fluss-flink/fluss-flink-2.1/src/test/java/com/alibaba/fluss/flink/source/Flink21TableSourceBatchITCase.java, fluss-flink/fluss-flink-2.1/src/test/java/com/alibaba/fluss/flink/source/Flink21TableSourceFailOverITCase.java, fluss-flink/fluss-flink-2.1/src/test/java/com/alibaba/fluss/flink/source/Flink21TableSourceITCase.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/adapter/CatalogTableAdapter.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/adapter/SingleThreadFetcherManagerAdapter.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/adapter/SingleThreadMultiplexSourceReaderBaseAdapter.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/catalog/FlinkCatalog.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/source/reader/FlinkSourceReader.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/source/reader/fetcher/FlinkSourceFetcherManager.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/utils/FlinkConversions.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/catalog/FlinkCatalogTest.java, fluss-flink/pom.xml, fluss-test-coverage/pom.xml, pom.xml
Linked issue: close #651 
* Add IT to test catalog, source and sink.
* Try [Engine Flink - Get Started](https://alibaba.github.io/fluss-docs/docs/engine-flink/getting-started/) in flink 2.0 with connector jar.
=> [flink] Support flink 2.1

fluss-lake/fluss-lake-lance/src/main/java/com/alibaba/fluss/lake/lance/tiering/LanceLakeCommitter.java
https://github.com/apache/fluss/pull/1441 fails CI because it doesn't rebase the master. The imported packages from that pull request have already been renamed.
=> [hotfix] fix Lance connector import package name

fluss-server/src/main/java/org/apache/fluss/server/coordinator/CoordinatorEventProcessor.java, fluss-server/src/main/java/org/apache/fluss/server/coordinator/statemachine/ReplicaStateMachine.java, fluss-server/src/test/java/org/apache/fluss/server/coordinator/statemachine/ReplicaStateMachineTest.java, fluss-server/src/test/java/org/apache/fluss/server/zk/ZooKeeperClientTest.java
Accelerate deleting tables and partitions by merge zk update requests.
Linked issue: close #1054
=> [server] Accelerate deleting table or partition

fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/source/FlinkTableSource.java, fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/utils/LakeSourceUtils.java, fluss-flink/fluss-flink-common/src/test/java/org/apache/fluss/flink/source/testutils/FlinkRowAssertionsUtils.java, fluss-lake/fluss-lake-paimon/src/test/java/org/apache/fluss/lake/paimon/flink/FlinkUnionReadFromTimestampITCase.java, fluss-lake/fluss-lake-paimon/src/test/java/org/apache/fluss/lake/paimon/flink/FlinkUnionReadTestBase.java, fluss-lake/fluss-lake-paimon/src/test/java/org/apache/fluss/lake/paimon/testutils/FlinkPaimonTieringTestBase.java, fluss-lake/fluss-lake-paimon/src/test/java/org/apache/fluss/lake/paimon/tiering/PaimonTieringITCase.java, fluss-lake/fluss-lake-paimon/src/test/java/org/apache/fluss/lake/paimon/tiering/ReCreateSameTableAfterTieringTest.java, fluss-server/src/main/java/org/apache/fluss/server/log/remote/RemoteLogManager.java, fluss-server/src/main/java/org/apache/fluss/server/replica/ReplicaManager.java
=> [flink] Union read in stream mode should support read from given timestamp

website/docs/maintenance/observability/monitor-metrics.md
…mentation
Linked issue: close #1610
=> [docs] Add FETCH_LOG monitoring metrics to Fluss monitor-metrics doc

fluss-lake/fluss-lake-iceberg/src/main/java/org/apache/fluss/lake/iceberg/maintenance/IcebergRewriteDataFiles.java, fluss-lake/fluss-lake-iceberg/src/main/java/org/apache/fluss/lake/iceberg/tiering/IcebergLakeWriter.java, fluss-lake/fluss-lake-iceberg/src/main/java/org/apache/fluss/lake/iceberg/utils/IcebergConversions.java, fluss-lake/fluss-lake-iceberg/src/test/java/org/apache/fluss/lake/iceberg/maintenance/IcebergRewriteITCase.java, fluss-lake/fluss-lake-iceberg/src/test/java/org/apache/fluss/lake/iceberg/testutils/FlinkIcebergTieringTestBase.java
=> [lake/iceberg] implement Iceberg log table compaction IT

fluss-server/src/main/java/org/apache/fluss/server/coordinator/CompletedSnapshotStoreManager.java, fluss-server/src/main/java/org/apache/fluss/server/kv/snapshot/CompletedSnapshot.java, fluss-server/src/main/java/org/apache/fluss/server/kv/snapshot/CompletedSnapshotHandle.java, fluss-server/src/main/java/org/apache/fluss/server/kv/snapshot/CompletedSnapshotStore.java, fluss-server/src/main/java/org/apache/fluss/server/zk/data/BucketSnapshot.java, fluss-server/src/test/java/org/apache/fluss/server/coordinator/CompletedSnapshotStoreManagerTest.java, fluss-server/src/test/java/org/apache/fluss/server/kv/snapshot/TestingCompletedSnapshotHandle.java
=> [kv] coordinator must handle inconsistency or broken snapshot scenarios

fluss-server/src/main/java/org/apache/fluss/server/kv/snapshot/CompletedSnapshot.java, fluss-server/src/main/java/org/apache/fluss/server/kv/snapshot/DefaultSnapshotContext.java, fluss-server/src/main/java/org/apache/fluss/server/kv/snapshot/SnapshotContext.java, fluss-server/src/main/java/org/apache/fluss/server/replica/Replica.java, fluss-server/src/test/java/org/apache/fluss/server/kv/snapshot/TestingCompletedKvSnapshotCommitter.java, fluss-server/src/test/java/org/apache/fluss/server/replica/ReplicaTest.java, fluss-server/src/test/java/org/apache/fluss/server/replica/ReplicaTestBase.java
=> [kv] TabletSever must handle inconsistency or broken snapshot scenarios.

website/docs/maintenance/tiered-storage/lakehouse-storage.md, website/docs/streaming-lakehouse/integrate-data-lakes/lance.md, website/docs/streaming-lakehouse/overview.md
=> [lake/lance] add documentation for Lance connector

fluss-lake/fluss-lake-iceberg/pom.xml, fluss-lake/fluss-lake-iceberg/src/main/java/org/apache/fluss/lake/iceberg/IcebergLakeCatalog.java, fluss-lake/fluss-lake-iceberg/src/main/java/org/apache/fluss/lake/iceberg/source/IcebergRecordAsFlussRow.java, fluss-lake/fluss-lake-iceberg/src/test/java/org/apache/fluss/lake/iceberg/source/IcebergRecordAsFlussRowTest.java, fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/PaimonLakeCatalog.java, fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/tiering/FlussRecordAsPaimonRow.java, fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/utils/PaimonRowAsFlussRow.java
Linked issue: close #1668
Introduce IcebergRecordAsFlussRow for iceberg union read
Introduce IcebergRecordAsFlussRow for iceberg union read
IcebergRecordAsFlussRowTest
=> [lake/iceberg] Introduce IcebergRecordAsFlussRow for iceberg union read

website/docs/maintenance/tiered-storage/lakehouse-storage.md, website/docs/streaming-lakehouse/integrate-data-lakes/iceberg.md, website/docs/streaming-lakehouse/integrate-data-lakes/lance.md
Linked issue: close #1333 
Introduce document for iceberg for end users to get started with for Fluss and Iceberg integration
Added new iceberg.md file
Modified lakehouse-storage.md to help enable iceberg as lakehouse storage 
None
None
None
=> [lake/iceberg] Add iceberg documents for lakehouse support in fluss

fluss-server/src/main/java/org/apache/fluss/server/coordinator/event/CoordinatorEventManager.java, fluss-server/src/main/java/org/apache/fluss/server/metrics/group/CoordinatorEventMetricGroup.java, fluss-server/src/main/java/org/apache/fluss/server/metrics/group/CoordinatorMetricGroup.java, website/docs/maintenance/observability/monitor-metrics.md
=> [coordinator] coordinator report event enqueue rate and event process time labeled by event_type

fluss-server/src/main/java/org/apache/fluss/server/replica/Replica.java
[hotfix] add tableBucket info for the print log while shrinking isr
=> [hotfix] add tableBucket info for the print log while shrinking isr

website/docs/maintenance/operations/upgrade-notes-0.8.md
Linked issue: close #1694
Add Metrics Updates to the Upgrade Notes 0.8
=> [docs] Add Metrics Updates to the Upgrade Notes

fluss-common/src/main/java/org/apache/fluss/metrics/MetricNames.java, fluss-server/src/main/java/org/apache/fluss/server/coordinator/CompletedSnapshotStoreManager.java, fluss-server/src/main/java/org/apache/fluss/server/coordinator/CoordinatorEventProcessor.java, fluss-server/src/main/java/org/apache/fluss/server/kv/snapshot/CompletedSnapshotStore.java, fluss-server/src/main/java/org/apache/fluss/server/kv/snapshot/PeriodicSnapshotManager.java, fluss-server/src/main/java/org/apache/fluss/server/kv/snapshot/SharedKvFileRegistry.java, fluss-server/src/main/java/org/apache/fluss/server/log/LogTablet.java, fluss-server/src/main/java/org/apache/fluss/server/log/remote/LogTieringTask.java, fluss-server/src/main/java/org/apache/fluss/server/log/remote/RemoteLogManager.java, fluss-server/src/main/java/org/apache/fluss/server/log/remote/RemoteLogManifest.java, fluss-server/src/main/java/org/apache/fluss/server/log/remote/RemoteLogTablet.java, fluss-server/src/main/java/org/apache/fluss/server/metrics/group/BucketMetricGroup.java, fluss-server/src/main/java/org/apache/fluss/server/metrics/group/CoordinatorMetricGroup.java, fluss-server/src/main/java/org/apache/fluss/server/replica/Replica.java, fluss-server/src/main/java/org/apache/fluss/server/replica/ReplicaManager.java, fluss-server/src/test/java/org/apache/fluss/server/coordinator/CompletedSnapshotStoreManagerTest.java, fluss-server/src/test/java/org/apache/fluss/server/coordinator/CoordinatorEventProcessorTest.java, website/docs/maintenance/observability/monitor-metrics.md
Linked issue: #1547 
This pr is aims to introduce some Server-Level Storage Aggregation Metrics.
=> [metrics] Adding Server-Level Storage Aggregation Metrics

fluss-client/src/test/java/org/apache/fluss/client/table/TypedPartitionedTableITCase.java, fluss-common/src/main/java/org/apache/fluss/utils/PartitionNameConverters.java, fluss-common/src/main/java/org/apache/fluss/utils/PartitionUtils.java
This is a post-review improvement for https://github.com/apache/fluss/pull/1264 (support primitive types for partition fields). 
1. Added result verification for the typed partition IT cases, and fixed the failure issues in the test
2. Renamed `NewPartitionedTableITCase` to `TypedPartitionedTableITCase`. 
3. Moved `PartitionNameConverters` from `org.apache.fluss.types` to `org.apache.fluss.utils` package, as it is not a type.
=> [client] Add result verification for the typed partition IT cases

fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/tiering/committer/FlussTableLakeSnapshot.java, fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/tiering/committer/FlussTableLakeSnapshotCommitter.java, fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/tiering/committer/TieringCommitOperator.java, fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/tiering/source/TableBucketWriteResult.java, fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/tiering/source/TableBucketWriteResultSerializer.java, fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/tiering/source/TieringSplitReader.java, fluss-flink/fluss-flink-common/src/test/java/org/apache/fluss/flink/tiering/committer/TieringCommitOperatorTest.java, fluss-flink/fluss-flink-common/src/test/java/org/apache/fluss/flink/tiering/source/TableBucketWriteResultSerializerTest.java, fluss-rpc/src/main/proto/FlussApi.proto, fluss-server/src/main/java/org/apache/fluss/server/entity/LakeBucketOffset.java, fluss-server/src/main/java/org/apache/fluss/server/log/LogTablet.java, fluss-server/src/main/java/org/apache/fluss/server/replica/ReplicaManager.java, fluss-server/src/main/java/org/apache/fluss/server/utils/ServerRpcMessageUtils.java, fluss-server/src/main/java/org/apache/fluss/server/zk/ZooKeeperClient.java, fluss-server/src/main/java/org/apache/fluss/server/zk/data/LakeTableSnapshot.java, fluss-server/src/main/java/org/apache/fluss/server/zk/data/LakeTableSnapshotJsonSerde.java, fluss-server/src/test/java/org/apache/fluss/server/replica/CommitLakeTableSnapshotITCase.java, fluss-server/src/test/java/org/apache/fluss/server/replica/NotifyReplicaLakeTableOffsetTest.java, fluss-server/src/test/java/org/apache/fluss/server/zk/data/LakeTableSnapshotJsonSerdeTest.java
=> [server] Lake tiering service report the max timestamp of fluss record

fluss-lake/fluss-lake-iceberg/src/main/java/org/apache/fluss/lake/iceberg/source/FlussRowAsIcebergRecord.java, fluss-lake/fluss-lake-iceberg/src/main/java/org/apache/fluss/lake/iceberg/source/IcebergLakeSource.java, fluss-lake/fluss-lake-iceberg/src/main/java/org/apache/fluss/lake/iceberg/source/IcebergRecordReader.java, fluss-lake/fluss-lake-iceberg/src/main/java/org/apache/fluss/lake/iceberg/source/IcebergSplitPlanner.java, fluss-lake/fluss-lake-iceberg/src/main/java/org/apache/fluss/lake/iceberg/tiering/FlussRecordAsIcebergRecord.java, fluss-lake/fluss-lake-iceberg/src/main/java/org/apache/fluss/lake/iceberg/tiering/RecordWriter.java, fluss-lake/fluss-lake-iceberg/src/main/java/org/apache/fluss/lake/iceberg/utils/FlussToIcebergPredicateConverter.java, fluss-lake/fluss-lake-iceberg/src/main/java/org/apache/fluss/lake/iceberg/utils/IcebergConversions.java, fluss-lake/fluss-lake-iceberg/src/test/java/org/apache/fluss/lake/iceberg/flink/FlinkUnionReadLogTableITCase.java, fluss-lake/fluss-lake-iceberg/src/test/java/org/apache/fluss/lake/iceberg/source/IcebergLakeSourceTest.java, fluss-lake/fluss-lake-iceberg/src/test/java/org/apache/fluss/lake/iceberg/utils/FlussToIcebergPredicateConverterTest.java, fluss-lake/fluss-lake-iceberg/src/test/java/org/apache/fluss/lake/iceberg/utils/IcebergConversionsTest.java, fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/source/PaimonLakeSource.java
=> [lake/iceberg] Iceberg read implementation supports filter push down

fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/tiering/source/TieringSplitReader.java, fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/tiering/RecordWriter.java, fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/tiering/mergetree/MergeTreeWriter.java, fluss-lake/fluss-lake-paimon/src/test/java/org/apache/fluss/lake/paimon/testutils/FlinkPaimonTieringTestBase.java, fluss-lake/fluss-lake-paimon/src/test/java/org/apache/fluss/lake/paimon/tiering/PaimonTieringITCase.java, fluss-lake/fluss-lake-paimon/src/test/java/org/apache/fluss/lake/paimon/tiering/ReCreateSameTableAfterTieringTest.java
=> [lake/paimon] Support tiering paimon deletion vector enabled table

fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/source/enumerator/FlinkSourceEnumerator.java, fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/source/enumerator/WorkerExecutor.java, fluss-flink/fluss-flink-common/src/test/java/org/apache/fluss/flink/source/enumerator/FlinkSourceEnumeratorTest.java, fluss-flink/fluss-flink-common/src/test/java/org/apache/fluss/flink/source/enumerator/MockWorkExecutor.java
=> [flink] Fluss enumerator partition discovery in fixed delay rather than fixed rate.

fluss-rpc/src/main/java/org/apache/fluss/rpc/netty/client/NettyClient.java, fluss-rpc/src/main/java/org/apache/fluss/rpc/netty/client/ServerConnection.java, fluss-rpc/src/test/java/org/apache/fluss/rpc/netty/client/NettyClientTest.java, fluss-rpc/src/test/java/org/apache/fluss/rpc/netty/client/ServerConnectionTest.java
=> [client] Fix exception occurs when initializing server connection.

fluss-common/src/main/java/org/apache/fluss/metrics/MetricNames.java, fluss-server/src/main/java/org/apache/fluss/server/log/LogTablet.java, fluss-server/src/main/java/org/apache/fluss/server/replica/Replica.java, website/docs/maintenance/observability/monitor-metrics.md
=> [lake] Introduce lake lag metrics for datalake enabled table

fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/source/enumerator/FlinkSourceEnumerator.java, fluss-lake/fluss-lake-iceberg/pom.xml, fluss-lake/fluss-lake-iceberg/src/main/java/org/apache/fluss/lake/iceberg/tiering/IcebergLakeCommitter.java, fluss-lake/fluss-lake-iceberg/src/main/resources/META-INF/NOTICE, website/docs/streaming-lakehouse/integrate-data-lakes/iceberg.md
Fix some bugs of iceberg tiering and improve iceberg document
=> [hotfix] Fix commit bugs of iceberg and improve document

fluss-client/src/main/java/org/apache/fluss/client/admin/FlussAdmin.java, fluss-rpc/src/main/java/org/apache/fluss/rpc/gateway/AdminGateway.java, fluss-rpc/src/main/proto/FlussApi.proto, fluss-server/src/main/java/org/apache/fluss/server/coordinator/CoordinatorService.java, fluss-server/src/test/java/org/apache/fluss/server/coordinator/TableManagerITCase.java, fluss-server/src/test/java/org/apache/fluss/server/coordinator/TestCoordinatorGateway.java, fluss-server/src/test/java/org/apache/fluss/server/testutils/RpcMessageTestUtils.java
=> [server] feat: support multiple table change types

README.md
I often use DeepWiki to understand and search for code. However, the code on DeepWiki may not be the latest. We need to add a badge to enable the code to be updated automatically. This can also be helpful for newcomers to use.
=> [docs] Automatically update the code of the fluss repository on deepwiki
