website/docs/engine-flink/ddl.md, website/docs/engine-flink/getting-started.md
Download Flink and shell commands do not match
=> [docs]Download Flink and shell commands do not match, in the engine link/setting started page

website/docs/quickstart/flink.md
add version to compatible docker-compose lower version, for docker-compose 1.2x.x, execute `docker-compose up -d` will meet the following problem:
=> [docs][quick-start] add version to compatible docker-compose lower version

fluss-client/src/main/java/com/alibaba/fluss/client/write/RoundRobinBucketAssigner.java, fluss-client/src/main/java/com/alibaba/fluss/client/write/WriterClient.java
Fix round-robin strategy name typo.
=> [fix] Fix round-robin strategy name typo

.github/workflows/ci.yaml, fluss-client/src/test/java/com/alibaba/fluss/client/admin/FlussAdminITCase.java, fluss-client/src/test/java/com/alibaba/fluss/client/scanner/log/FlussLogScannerITCase.java, fluss-client/src/test/java/com/alibaba/fluss/client/scanner/log/RemoteLogDownloaderTest.java, fluss-client/src/test/java/com/alibaba/fluss/client/table/FlussPartitionedTableITCase.java, fluss-client/src/test/java/com/alibaba/fluss/client/table/FlussTableITCase.java, fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/catalog/FlinkCatalogTest.java, fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/utils/FlinkConnectorOptionsUtilTest.java, fluss-filesystems/fluss-fs-oss/src/test/java/com/alibaba/fluss/fs/oss/OSSTestCredentials.java, fluss-filesystems/fluss-fs-oss/src/test/java/com/alibaba/fluss/fs/oss/OSSWithTokenFileSystemBehaviorITCase.java, fluss-lakehouse/fluss-lakehouse-paimon/src/test/java/com/alibaba/fluss/lakehouse/paimon/flink/FlinkUnionReadLogTableITCase.java, fluss-lakehouse/fluss-lakehouse-paimon/src/test/java/com/alibaba/fluss/lakehouse/paimon/flink/LakeTableEnumeratorTest.java, fluss-lakehouse/fluss-lakehouse-paimon/src/test/java/com/alibaba/fluss/lakehouse/paimon/testutils/PaimonSyncTestBase.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/server/RequestChannel.java, fluss-rpc/src/test/java/com/alibaba/fluss/rpc/protocol/RequestChannelTest.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorRequestBatch.java, fluss-server/src/main/java/com/alibaba/fluss/server/utils/RpcMessageUtils.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/CoordinatorEventProcessorTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/TableManagerITCase.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/event/watcher/TableChangeWatcherTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/log/remote/RemoteLogITCase.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/KvReplicaRestoreITCase.java, fluss-server/src/test/java/com/alibaba/fluss/server/testutils/FlussClusterExtension.java, fluss-test-coverage/pom.xml
Enable ci for fluss
N/A
N/A
N/A
=> [build] Enable ci

fluss-client/src/main/java/com/alibaba/fluss/client/lookup/LookupSender.java, fluss-client/src/test/java/com/alibaba/fluss/client/admin/ClientToServerITCaseBase.java, fluss-client/src/test/java/com/alibaba/fluss/client/table/FlussTableITCase.java, fluss-server/src/test/java/com/alibaba/fluss/server/testutils/FlussClusterExtension.java
Linked issue: https://github.com/alibaba/fluss/issues/172
In tests, create a table with lots of buckets, and then lookup while leader and bucket not ready yet, you can find the LookupSender will hang forever.
See `FlussTableITCase#testLookupForNotReadyTable()`, if you remove ` waitAllReplicasReady(tableId, descriptor)`,  this bug will happend.
=> [client] Fix some error which will let LookupSender hang if leader and bucket not ready

fluss-client/src/test/java/com/alibaba/fluss/client/admin/FlussAdminITCase.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/TableManagerITCase.java
Linked issue: https://github.com/alibaba/fluss/issues/175
Currently, `TableManagerITCase#testPartitionedTableManagement`, I suspect that the bucket count is set too large, which may introduce instability for the IT case.
=> [ci] Fix CI unstable for TableManagerITCase#testPartitionedTableManagement

website/docs/maintenance/tiered-storage/lakehouse-storage.md
Linked issue: close #190
Fixed error in documentation
n/a
n/a
n/a
=> [Doc] Fix wrong lakehouse storage key name in documentation

fluss-server/src/main/java/com/alibaba/fluss/server/replica/delay/DelayedOperationManager.java
Fix typo in DelayedOperationManager
=> [hotfix][typo] Fix typo in DelayedOperationManager

website/docs/maintenance/logging.md
The logging.md doc missing 2 colons. I guess they should be appended.
=> [docs] Fix colon missing in website/docs/maintenance/logging.md

fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/utils/FlinkRowToFlussRowConverter.java
fix [#255](https://github.com/alibaba/fluss/issues/225)
=> [connector] FlinkRowToFlussRowConverter pass byte[] rather than string From Flink StringData to Fluss BinaryString.

website/docusaurus.config.ts, website/package.json, website/static/manifest.json
Linked issue: close https://github.com/alibaba/fluss/issues/229
Support PWA (Progressive Web App) feature for website to make experience more user-friendly.
=> [website] Add PWA feature to website

pom.xml, tools/maven/checkstyle.xml, website/docs/dev/ide-setup.md
Linked issue: fix #220 
Here are the changes I made:
1. Upgraded to version 3.6.0 according to the information on the [official website](https://maven.apache.org/plugins/maven-checkstyle-plugin/history.html) (since Fluss is still compiled with JDK 8).
2. Removed invalid Checkstyle options.
3. Removed the NewlineAtEndOfFile check because it causes a significant number of Checkstyle errors when compiling on Windows (approximately 1,400 files fail to comply).
我做了如下改动：
1. 根据[官方网站](https://maven.apache.org/plugins/maven-checkstyle-plugin/history.html)提供的信息，升级到了3.6.0版本（因为fluss目前仍然是JDK8编译的）;
2. 删除无效的checkstyle选项;
3. 删除NewlineAtEndOfFile的检查。因为在windows上进行编译，会产生大量的checkstyle错误（大概1400多个文件不符合要求）。
=> [bug] update checkstyle-plugin version and doc

website/docs/dev/ide-setup.md
=> [docs] fix seq number error

fluss-client/src/main/java/com/alibaba/fluss/client/scanner/log/CompletedFetch.java, fluss-client/src/main/java/com/alibaba/fluss/client/scanner/log/DefaultCompletedFetch.java, fluss-client/src/main/java/com/alibaba/fluss/client/scanner/log/FlussLogScanner.java, fluss-client/src/main/java/com/alibaba/fluss/client/scanner/log/LogFetcher.java, fluss-client/src/main/java/com/alibaba/fluss/client/scanner/log/RemoteCompletedFetch.java, fluss-client/src/main/java/com/alibaba/fluss/client/scanner/log/RemotePendingFetch.java, fluss-client/src/main/java/com/alibaba/fluss/client/table/FlussTable.java, fluss-client/src/test/java/com/alibaba/fluss/client/scanner/log/DefaultCompletedFetchTest.java, fluss-client/src/test/java/com/alibaba/fluss/client/scanner/log/LogFetchBufferTest.java, fluss-client/src/test/java/com/alibaba/fluss/client/scanner/log/LogFetchCollectorTest.java, fluss-client/src/test/java/com/alibaba/fluss/client/scanner/log/RemoteCompletedFetchTest.java, fluss-client/src/test/java/com/alibaba/fluss/client/scanner/log/RemoteLogScannerITCase.java, fluss-client/src/test/java/com/alibaba/fluss/client/table/FlussTableITCase.java, fluss-common/src/main/java/com/alibaba/fluss/record/LogRecordReadContext.java, fluss-common/src/main/java/com/alibaba/fluss/types/RowType.java, fluss-common/src/main/java/com/alibaba/fluss/utils/Projection.java, fluss-common/src/test/java/com/alibaba/fluss/record/FileLogProjectionTest.java, fluss-common/src/test/java/com/alibaba/fluss/testutils/DataTestUtils.java, fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/source/FlinkTableSourceITCase.java, fluss-server/src/test/java/com/alibaba/fluss/server/kv/KvTabletTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/ReplicaTest.java
Linked issue:  https://github.com/alibaba/fluss/issues/150
Even if Fluss only support projection push down to server for log format as ARROW. However, INDEXED format also need to support projection push down in client side. This pr is aims to fix this bug.
=> [client] Indexed row support projection

fluss-client/src/main/java/com/alibaba/fluss/client/scanner/snapshot/SnapshotFilesReader.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/FlinkTableSource.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/lookup/FlinkAsyncLookupFunction.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/lookup/FlinkLookupFunction.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/lookup/LookupNormalizer.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/utils/FlinkUtils.java, fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/source/FlinkTableSourceITCase.java
project row to avoid deserialize unnecessary fields
=> [flink](lookup) project row to avoid deserialize unnecessary fields 

fluss-client/src/test/java/com/alibaba/fluss/client/table/FlussTableITCase.java, fluss-common/src/main/java/com/alibaba/fluss/config/ConfigOptions.java, fluss-common/src/main/java/com/alibaba/fluss/metadata/MergeEngine.java, fluss-common/src/main/java/com/alibaba/fluss/metadata/TableDescriptor.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/catalog/FlinkTableFactory.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/sink/FlinkTableSink.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/FlinkTableSource.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/utils/FlinkConversions.java, fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/sink/FlinkTableSinkITCase.java, fluss-lakehouse/fluss-lakehouse-paimon/src/test/java/com/alibaba/fluss/lakehouse/paimon/testutils/TestingDatabaseSyncSink.java, fluss-server/src/main/java/com/alibaba/fluss/server/kv/KvManager.java, fluss-server/src/main/java/com/alibaba/fluss/server/kv/KvTablet.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/Replica.java, fluss-server/src/test/java/com/alibaba/fluss/server/kv/KvManagerTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/kv/KvTabletTest.java
Linked issue: close #133
Introduce first row merge engine for primary key table
FlussTableITCase#testFirstRowMergeEngine
FlinkTableSinkITCase#testFirstRowMergeEngine
N/A
I'd like to complete the document in another pr #241  since after introduce merge engine, we may need to refactor the document struture about primary key table.
=> [kv] Support first row merge engine

fluss-client/src/main/java/com/alibaba/fluss/client/admin/Admin.java, fluss-client/src/main/java/com/alibaba/fluss/client/admin/FlussAdmin.java, fluss-client/src/test/java/com/alibaba/fluss/client/admin/FlussAdminITCase.java, fluss-common/src/main/java/com/alibaba/fluss/cluster/ServerNode.java
Linked issue: close #282 
com.alibaba.fluss.client.admin.FlussAdminITCase#testGetCluster
```java
public interface Admin extends AutoCloseable {
/**
* Get the current cluster information. asynchronously.
*
* @param tablePaths table paths to be included in the metadata.
* @param tablePartitions table partitions to be included in the metadata.
* @param tablePartitionIds table partition ids to be included in the metadata.
*/
CompletableFuture<Cluster> getCluster(
@Nullable Set<TablePath> tablePaths,
@Nullable Collection<PhysicalTablePath> tablePartitions,
@Nullable Collection<Long> tablePartitionIds);
```
=> [client][admin] Admin provide interface to get cluster information.

fluss-metrics/fluss-metrics-jmx/src/test/java/com/alibaba/fluss/metrics/jmx/JMXReporterTest.java, fluss-metrics/fluss-metrics-prometheus/src/test/java/com/alibaba/fluss/metrics/prometheus/PrometheusReporterDifferentLabelValueTest.java, fluss-server/src/main/java/com/alibaba/fluss/server/metrics/group/PhysicalTableMetricGroup.java
Linked issue: close #302 
See changes in 
- `com.alibaba.fluss.metrics.prometheus.PrometheusReporterDifferentLabelValueTest`
- `com.alibaba.fluss.metrics.jmx.JMXReporterTest`
Additional manually verification by creating the following 2 tables 
```
CREATE TABLE tbl1(
a STRING,
b INT,
PRIMARY KEY(a, b) NOT ENFORCED 
) PARTITIONED BY (a) WITH (
'table.auto-partition.enabled' = 'true',
'table.auto-partition.time-unit' = 'YEAR',
'table.auto_partitioning.time-zone' = 'Asia/Shanghai'
);
CREATE TABLE tbl2(
c STRING,
d INT,
PRIMARY KEY(c,d) NOT ENFORCED 
);
```
in the Flink SQL client and check if all metrics are reported in Prometheus and JMX.
**Prometheus**
**JMX** (non-partitioned tables have a single entry with an empty string as key)
n/a
n/a
=> [hotfix] Report empty string as value for partition label for non-partitioned table

fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/NettyUtils.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/server/NettyServer.java, fluss-rpc/src/test/java/com/alibaba/fluss/rpc/netty/client/NettyClientTest.java
Linked issue: close #278 
Temporary bind-port error should not shutdown server
=> [rpc] Fix detecting bind failure in case of Netty EPOLL transport

fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/sink/FlinkSinkFunction.java
in https://github.com/alibaba/fluss/issues/283, there is also an abnormal log for multiple times:
```java
WARN  com.alibaba.fluss.client.write.Sender                        [] - Get error write response on table bucket TableBucket{tableId=2, bucket=152}, fail. Error: UNKNOWN_SERVER_ERROR. Error Message: java.lang.IllegalArgumentException: The log sequence number must be non-decreasing. The current log sequence number is 600582, but the new log sequence number is 600581
at com.alibaba.fluss.server.kv.prewrite.KvPreWriteBuffer.update(KvPreWriteBuffer.java:126)
```
the coresponing code is com.alibaba.fluss.client.write.Sender#handleWriteBatchException.
```java
private Set<PhysicalTablePath> handleWriteBatchException(
WriteBatch writeBatch, ApiError error) {
Set<PhysicalTablePath> …
```
=> [hotfix][connector] Fix sink not stop when exception is occurs.

fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/source/FlinkTableSourceITCase.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/entity/ListOffsetsResultForBucket.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/entity/ResultForBucket.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/Replica.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/ReplicaManager.java, fluss-server/src/main/java/com/alibaba/fluss/server/tablet/TabletServer.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/ReplicaManagerTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/ReplicaTestBase.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/fetcher/ReplicaFetcherThreadTest.java
=> [connector] Fluss support scan.startup.timestamp is larger than max timestamp of bucket.

fluss-client/src/main/java/com/alibaba/fluss/client/metadata/MetadataUpdater.java, fluss-client/src/main/java/com/alibaba/fluss/client/scanner/log/LogFetcher.java, fluss-common/src/main/java/com/alibaba/fluss/cluster/BucketLocation.java, fluss-common/src/main/java/com/alibaba/fluss/cluster/Cluster.java, fluss-common/src/test/java/com/alibaba/fluss/cluster/ClusterTest.java
It try to fix the follow exception that may be thrown by client
```
nCaused by: java.lang.StackOverflowError\n\tat java.util.Collections$UnmodifiableCollection$1.<init>
(Collections.java:1041) ~[?:1.8.0_372]\n\tat java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1040) ~[?:1.8.0_372]
java.util.Collections$UnmodifiableCollection$1.<init>(Collections.java:1041) ~[?:1.8.0_372]
java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1040) ~[?:1.8.0_372]\njava.util.Collections$UnmodifiableCollection$1.<init>(Collections.java:1041) ~[?:1.8.0_372]
java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1040) ~[?:1.8.0_372]
java.util.Collections$UnmodifiableCollection$1.<init>(Collections.java:1041) ~[?:1.8.0_372] …
```
=> [hotfix] Fix stack overflow exception for cluster metadata in client

fluss-client/src/test/java/com/alibaba/fluss/client/table/FlussTableITCase.java, fluss-client/src/test/java/com/alibaba/fluss/client/write/ArrowLogWriteBatchTest.java, fluss-client/src/test/java/com/alibaba/fluss/client/write/RecordAccumulatorTest.java, fluss-common/src/main/java/com/alibaba/fluss/compression/ArrowCompressionInfo.java, fluss-common/src/main/java/com/alibaba/fluss/compression/ArrowCompressionRatioEstimator.java, fluss-common/src/main/java/com/alibaba/fluss/record/MemoryLogRecordsArrowBuilder.java, fluss-common/src/main/java/com/alibaba/fluss/row/arrow/ArrowWriter.java, fluss-common/src/main/java/com/alibaba/fluss/row/arrow/ArrowWriterPool.java, fluss-common/src/test/java/com/alibaba/fluss/compression/ArrowCompressionRatioEstimatorTest.java, fluss-common/src/test/java/com/alibaba/fluss/row/arrow/ArrowReaderWriterTest.java
https://github.com/alibaba/fluss/issues/326
We have introduced arrow compression in https://github.com/alibaba/fluss/issues/187. However, Currently, the client calculates the batch size using the data before compress, which would cause a discrepancy between the actual batch size sent to the server and the batch size configured by the user, and in turn affects the compression efficiency. Therefore, in this pr we will introduce an estimator to continuously update the latest compression ratio in client, making the compressed batch size closer to the user's specified value.
=> [log] Arrow Compression support estimate compression ratio in client

fluss-common/src/main/java/com/alibaba/fluss/utils/BytesUtils.java, fluss-server/src/main/java/com/alibaba/fluss/server/kv/rocksdb/RocksDBKv.java
Linked issue: https://github.com/alibaba/fluss/issues/271
Currently, `RocksDBKv#isPrefixEquals()` very inefficient to compare arrays byte by byte. Java9 provides a more efficient way [Arrays.compare(compare(byte[] a, int aFromIndex, int aToIndex, byte[] b, int bFromIndex, int bToIndex))](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Arrays.html#compare(byte%5B%5D,int,int,byte%5B%5D,int,int)), underlying it leverages SIMD instructions.
As it is only supported since Java9, In this pr, we implement it  based on the running jdk env (the method can get the running JDK environment, if Java9 use the support Arrays.compare() method).
=> [kv] Use JDK9 Arrays#compare() to check bytes prefix for PrefixLookup

fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorServer.java
Reuse generated server id rather than generate a new one
=> [bug] Remove unnecessary generation of CoordinatorServer server id

fluss-client/src/main/java/com/alibaba/fluss/client/metadata/MetadataUpdater.java
fix #344 
In method `MetadataUpdater`#leaderFor , we should check whether the table bucket is for a partition.
Not applicable.
Not applicable.
=> [bug][client] check table bucket is for a partition and update info

fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/FlinkConnectorOptions.java, fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/sink/FlinkTableSinkITCase.java
Rename connector option key from "sink.ignore_delete" to "sink.ignore-delete". Using dash to keep align with all other config option styles. 
Covered  by `FlinkTableSinkITCase#testIgnoreDelete`.
=> [flink] Fix connector option "sink.ignore_delete" to "sink.ignore-delete"

fluss-common/src/main/java/com/alibaba/fluss/record/MemoryLogRecordsArrowBuilder.java, fluss-common/src/test/java/com/alibaba/fluss/record/MemoryLogRecordsArrowBuilderTest.java
Linked issue: https://github.com/alibaba/fluss/issues/353
When MemoryLogRecordsArrowBuilder try to resetWriterState in case the produceLog request failed and the batch is re-enqueue to send with different write state, we will reset the bytesView to null, this is very dangerous. Because once we set bytesView to null, we won't be able to retrieve the data from arrowWriter while next build, which means data in this batch will be lost. The correct approach is to simply reset the batch header instead of reset the whole batch.
This pr is aims to fix this error by introducing a bool variable `resetBatchHeader` to reset batch header while next build call.
=> [client] Fix the possible data loss error while MemoryLogRecordsArrowBuilder#resetWriterState

fluss-common/src/main/java/com/alibaba/fluss/metrics/MetricNames.java, fluss-server/src/main/java/com/alibaba/fluss/server/kv/KvTablet.java, fluss-server/src/main/java/com/alibaba/fluss/server/kv/prewrite/KvPreWriteBuffer.java, fluss-server/src/main/java/com/alibaba/fluss/server/log/LogAppendInfo.java, fluss-server/src/main/java/com/alibaba/fluss/server/log/LogTablet.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/Replica.java, fluss-server/src/test/java/com/alibaba/fluss/server/kv/KvTabletTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/kv/prewrite/KvPreWriteBufferTest.java, website/docs/maintenance/monitor-metrics.md
Linked issue: https://github.com/alibaba/fluss/issues/325
Currently, the `kv pre-write buffer` writes data into the buffer before submitting the CDC log. However, for duplicate KV batches, the duplicated CDC logs that we submit will not be written to disk by the logTablet, and the logEndOffset will not be increase. This results in `the MSN` in the `pre-write buffer` being greater than the `logEndOffset`, leading to an error. The purpose of this PR is to fix this issue. If we detect a duplicate KV batch, the data that has already been written into the `pre-write buffer` needs to be truncated.
Also, I add some metrics to avoid print so much logs when duplicated or error happend in `pre-write buffer`.
=> [kv] The kv pre-write buffer need to truncate while receive duplicated batches

fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/FlinkConnectorOptions.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/FlinkTableSource.java, fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/source/FlinkTableSourceITCase.java, website/docs/engine-flink/reads.md
Linked issue: close #346
The default value of `scan.startup.mode` is `initial` at present, which means `perform an initial snapshot first, and then continue read latest logs`. The `initial` name is confusing for users that it only performs the "initial snapshot". `full` is a better name that reads the full content/data from the table. For streaming mode, it produces the latest snapshot on the table (no matter Log Table or Primary Key Table) upon first startup, and continue to read the latest logs. For batch mode, it just produces the latest snapshot but does not read new logs. The `full` word reflects it reads all data in batch mode, and read all data for current and future in streaming mode. Paimon also uses [`full`](https://paimon.apache.org/docs/master/maintenance/configurations/) for …
=> [flink] Change the name of default value from initial to full for scan.startup.mode option

fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/lakehouse/paimon/split/PaimonSnapshotAndFlussLogSplitState.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/lakehouse/paimon/split/PaimonSnapshotSplitState.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/emitter/FlinkRecordEmitter.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/split/HybridSnapshotLogSplitState.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/split/LogSplitState.java, fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/source/state/SourceSplitStateTest.java, fluss-lakehouse/fluss-lakehouse-paimon/src/main/java/com/alibaba/fluss/lakehouse/paimon/source/emitter/FlinkRecordEmitter.java, fluss-lakehouse/fluss-lakehouse-paimon/src/main/java/com/alibaba/fluss/lakehouse/paimon/source/split/HybridSnapshotLogSplitState.java, fluss-lakehouse/fluss-lakehouse-paimon/src/main/java/com/alibaba/fluss/lakehouse/paimon/source/split/LogSplitState.java, fluss-lakehouse/fluss-lakehouse-paimon/src/test/java/com/alibaba/fluss/lakehouse/paimon/source/state/SourceSplitStateTest.java
Linked issue: close #358
To fix the issue that split will lose offset when restore from state.
When init the SplitState from split, SplitState should use the logoffset from split to init.
UT: SourceSplitStateTest
IT: Let's add the IT that restore from savapoint in #280
=> [flink] Fix split will lose offset when restore from state

fluss-client/src/test/java/com/alibaba/fluss/client/admin/FlussAdminITCase.java, fluss-common/src/test/java/com/alibaba/fluss/record/TestData.java, fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/utils/FlinkConversionsTest.java, fluss-lakehouse/fluss-lakehouse-paimon/src/test/java/com/alibaba/fluss/lakehouse/paimon/sink/NewTableAddedPaimonListenerTest.java, fluss-server/src/main/java/com/alibaba/fluss/server/zk/data/DatabaseRegistration.java, fluss-server/src/main/java/com/alibaba/fluss/server/zk/data/TableRegistration.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/AutoPartitionManagerTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/event/watcher/TableChangeWatcherTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/zk/ZooKeeperClientTest.java
Set createdTime and modifiedTime to the same value during initial registration
Added UT in FlussAdminITCase for table registration and database registration
No
No
=> [hotfix][fluss-server] Set createdTime and modifiedTime to the same value during initial registration

fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/utils/FlinkConversions.java
In pr https://github.com/alibaba/fluss/pull/360, we change the way of building Flink `CatalogTable`, using `CatalogTable#newBuilder()` instead of `CatalogTable#of()` in `FlinkConversions#toFlinkTable()`. However, in lower version of Flink, like 'flink-1.17', `CatalogTable#newBuilder()` has not been introduced yet, so in order to maintain better compatibility with lower Flink versions, this PR will revert this change.
=> [hotfix] Revert build a Flink CatalogTable use CatalogTable#newBuilder() to backward compatible with lower Flink version

fluss-client/src/main/java/com/alibaba/fluss/client/lookup/PrefixKeyLookuper.java, fluss-client/src/main/java/com/alibaba/fluss/client/lookup/PrimaryKeyLookuper.java, fluss-client/src/main/java/com/alibaba/fluss/client/utils/ClientUtils.java
Currently, In `PrimaryKeyLookuper` and `PrefixKeyLookuper`, we will always initialize the `LakeTableBucketAssigner`, even if the table doesn't enable dataLake. Since the current implementation of `LakeTableBucketAssigner` will always load the Paimon dependency, this can lead to situations where the dependency is not found after the actual packaging. 
Therefore, in this PR, we have modified it to only initialize the `LakeTableBucketAssigner` when dataLake is enabled.
=> [hotfix] Don't initialize LakeTableBucketAssigner to avoid load unnecessary dependencies if dataLake disabled for target table

fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/NettyLogger.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/ClientChannelInitializer.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/server/ServerChannelInitializer.java
Linked issue: close #378
Support Netty level logging at the network layer for Fluss. To configure Netty level logging a LogHandler must be added to the channel pipeline. `NettyLogger` is introduced as a new class which is able to construct a log handler depending on the log level:
- In case of `<Logger name="com.alibaba.fluss.rpc.netty.NettyLogger;" level="DEBUG" additivity="false">`: a custom log handler is created which does not dump the message contents. This way the log is a bit more compact. Moreover when network level encryption is switched on this level might be sufficient.
- In case of `<Logger name="com.alibaba.fluss.rpc.netty.NettyLogger" level="TRACE" additivity="false">`: Netty's own log handler is used which dumps the message contents.
- Otherwise (when the logger is not …
=> [rpc] Support Netty Logging at the network layer

fluss-client/src/main/java/com/alibaba/fluss/client/admin/Admin.java, fluss-client/src/main/java/com/alibaba/fluss/client/admin/FlussAdmin.java, fluss-client/src/test/java/com/alibaba/fluss/client/admin/FlussAdminITCase.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/catalog/FlinkCatalog.java
Deprecate deleteTable/deleteDatabase with dropTable/dropDatabase
Linked issue: close #381
Covered via FlussAdminITCase
Yes, minor affects in client API, but Fluss doesn't has a client API documentation so far, we can introduce a API documentation later
=> [fluss-client] Deprecate deleteTable/deleteDatabase with dropTable/dropDatabase

fluss-client/src/test/java/com/alibaba/fluss/client/table/FlussTableITCase.java, fluss-common/src/main/java/com/alibaba/fluss/record/FileLogProjection.java, fluss-common/src/test/java/com/alibaba/fluss/record/TestData.java, fluss-common/src/test/java/com/alibaba/fluss/testutils/LogRecordBatchAssert.java, fluss-common/src/test/java/com/alibaba/fluss/testutils/LogRecordsAssert.java, fluss-server/src/test/java/com/alibaba/fluss/server/kv/KvTabletTest.java
Linked issue: https://github.com/alibaba/fluss/issues/416
This pr is aims to fix the IndexOutOfBoundsException when reading cdc log from pk table with projection. This case will happen when we create a primary key table with `FIRST_ROW` or  `VERSION_BASED` merge engine enable. As `FIRST_ROW` for example, we will generate cdc log batch which contains no records, however, if we try to read this cdc log batch with projection, we will incorrectly read the arrow header in `FileLogProjection` even if it was empty, this pr is trying to fix it.
=> [server] Fix the IndexOutOfBoundsException when reading cdc log from pk table with projection

fluss-dist/src/main/resources/bin/coordinator-server.sh
fix a typo on JVM param for adding coordinator-specific JVM options
=> [build] fix a build typo on start param

fluss-common/src/main/java/com/alibaba/fluss/metadata/TableInfo.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CompletedSnapshotStoreManager.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorContext.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorEventProcessor.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/CompletedSnapshotStoreManagerTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/CoordinatorEventProcessorTest.java
Linked issue: close #412 
Currently, when kv table is deleted or table partition is expired, memory still persist its kv snapshot, which causes memory leak. This pr will fix it.
**CompletedSnapshotStoreManagerTest::testRemoveCompletedSnapshotStoreFromManager**
=> [kv] when table(partition) is deleted, drop corresponding snapshots

fluss-common/src/main/java/com/alibaba/fluss/utils/FlussPaths.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CompletedSnapshotStoreManager.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorContext.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorEventProcessor.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorServer.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/RemoteStorageCleaner.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/TableManager.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/CompletedSnapshotStoreManagerTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/CoordinatorEventProcessorTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/TableManagerTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/statemachine/TableBucketStateMachineTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/KvSnapshotITCase.java, fluss-server/src/test/java/com/alibaba/fluss/server/testutils/FlussClusterExtension.java
Linked issue: close #296 
KvSnapshotITCase#testKvSnapshotAndDelete
=> [bug][coordinator/kv] delete remote kv dir for table on coordinator server

pom.xml, website/docs/engine-flink/getting-started.md, website/docs/quickstart/flink.md
Linked issue: close #449
Bump Flink version from 1.20.0 to 1.20.1.
No.
No.
`flink.md` and `getting-started.md` bump Flink version from 1.20.0 to 1.20.1.
=> [flink] Bump Flink version from 1.20.0 to 1.20.1

website/docs/maintenance/observability/quickstart.md
Add missing FLUSS_VERSION args for locally build fluss-slf4j-logback container image
n/a
n/a
n/a
=> [docs] Fix error in docker manifests in observability quickstart guide

.mvn/wrapper/maven-wrapper.properties, README.md, mvnw, mvnw.cmd, website/docs/dev/building.md, website/docs/dev/ide-setup.md
Linked issue: close #161 
Add Maven Wrapper to project.
n/a
n/a
n/a
=> [build] Add Maven Wrapper

fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/enumerator/FlinkSourceEnumerator.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/reader/FlinkSourceSplitReader.java, fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/source/FlinkTableSourceFailOverITCase.java
Linked issue: close #348 
This PR fixes an issue where removed partitions were still retained in the source reader’s state. Upon recovery, the source attempted to re-subscribe to non-existent partitions, leading to a `PartitionNotExistException`.
- **Mark Finished Splits on Partition Removal:**  
Active bounded splits are now marked as finished when a partition removal event is received. This prevents removed partitions from being restored.
- **Remove Pending Snapshot Splits and Unsubscribe Buckets:**  
Pending snapshot splits and subscribed log buckets associated with removed partitions are removed and unsubscribed respectively.
- **Filter Non-existent Partitions During Restore:**  
The `subscribeLog` method now catches `PartitionNotExistException` and logs a warning instead of failing, …
=> [connector] Fix partition state update and filter non-existent partitions on restore

fluss-common/pom.xml
Linked issue: close #475
Bump zstd-jni version from 1.4.9-1 to 1.5.7-1.
Backport https://github.com/apache/spark/pull/50057.
No.
No.
No.
=> [common] Bump zstd-jni version from 1.4.9-1 to 1.5.7-1

fluss-common/pom.xml, fluss-common/src/main/java/com/alibaba/fluss/compression/ZstdArrowCompressionCodec.java
Linked issue:  https://github.com/alibaba/fluss/issues/462
Currently, if we define a String in the table and stream write a very large size of data, such as a single row size 5k, the ZstdArrowCompressionCodec will definitely throw a RuntimeException with the message 'Destination buffer is too small' during decompression.
This pr is aims to fix this error.  Through investigation, we found that if we replace the compression way using `Zstd.compressUnsafe(long dst, long dstSize, long src, long srcSize, int level)` with memory copy methods like `Zstd.compressDirectByteBuffer(ByteBuffer dst, int dstOffset, int dstSize, ByteBuffer src, int srcOffset, int srcSize, int level)`, or switch to using `ZstdOutputStreamNoFinalizer`, the error no longer occurs. The possible reason is that the …
=> [log] Fix the 'Destination buffer is too small' error while decompress data in ZstdArrowCompressionCodec

fluss-common/pom.xml, fluss-common/src/main/java/com/alibaba/fluss/compression/FlussLZ4BlocakInputStream.java, fluss-common/src/main/java/com/alibaba/fluss/compression/FlussLZ4BlockOutputStream.java, fluss-common/src/main/java/com/alibaba/fluss/compression/Lz4ArrowCompressionCodec.java
Linked issue: https://github.com/alibaba/fluss/issues/463
Currently, if we try to use FRAME_LZ4 codec in flink job to do compress. The `Lz4ArrowCompressionCodec` gets stuck in the `FramedLZ4CompressorOutputStream` during compression and is unable to flush data. 
In this pr, we try to introduce a new compress inputsStream/decompress outputStream way refer to Kafka.
=> [log] Fix Lz4ArrowCompressionCodec gets stuck during compression and is unable to flush data error

fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/server/NettyServerHandler.java
Linked issue: close #377
Modify to debug level to avoid too many logs if NLB(Network Load Balancer is mounted.
=> [netty] Modify to debug level in NettyServerHandler#exceptionCaught method to avoid to many logs if NLB is mounted

fluss-common/src/main/java/com/alibaba/fluss/config/Password.java, fluss-common/src/main/java/com/alibaba/fluss/metadata/Schema.java
Linked issue: close #409
Declare `serialVersionUID` explicitly for serializable class `Password` and `Column`.
No.
No.
No.
=> [common] Declare serialVersionUID explicitly for serializable class

fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/sink/FlinkSink.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/sink/FlinkTableSink.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/sink/writer/AppendSinkWriter.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/sink/writer/FlinkSinkWriter.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/sink/writer/UpsertSinkWriter.java, fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/sink/FlinkSinkWriterTest.java, fluss-lakehouse/fluss-lakehouse-paimon/src/test/java/com/alibaba/fluss/lakehouse/paimon/source/FlussDatabaseSyncSourceITCase.java, fluss-lakehouse/fluss-lakehouse-paimon/src/test/java/com/alibaba/fluss/lakehouse/paimon/testutils/TestingDatabaseSyncSink.java, fluss-test-coverage/pom.xml
Linked issue: close #132
Upgrade sink connector from deprecated RichSinkFunction (will be removed in Flink 2.0) to new Sink interface
- UT (adapted to new implementation, test case logic unchanged): `com.alibaba.fluss.connector.flink.sink.FlinkSinkWriterTest.java`
- IT (_unchanged_, because external interface did not change): `com.alibaba.fluss.connector.flink.sink.FlinkTableSinkITCase.java`
n/a
n/a
=> [flink] Upgrade sink connector to new API version

fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/NettyClient.java
Linked issue: close #501
The `TCP_NODELAY` socket option allows your network to bypass Nagle Delays by disabling Nagle's algorithm, and sending the data as soon as it's available. Enabling `TCP_NODELAY` forces a socket to send the data in its buffer, whatever the packet size. To disable Nagle's buffering algorithm, use the `TCP_NODELAY` socket option. The `SO_KEEPALIVE` socket option is designed to allow an application to enable keep-alive packets for a socket connection. When the `SO_KEEPALIVE` option is enabled, TCP probes a connection that has been idle for some amount of time. The default value for this idle period is 2 hours which is too long for most applications. Support `NettyClient` enable `TCP_NODELAY` and `SO_KEEPALIVE`.
`NettyClient` enables `TCP_NODELAY` and `SO_KEEPALIVE`. …
=> [rpc] Support NettyClient enable TCP_NODELAY and SO_KEEPALIVE

fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/catalog/FlinkCatalogTest.java
Linked issue: close #477
Use `findThrowableWithMessage` to find the `KeeperException$NodeExistsException` message .
=> [hotfix] Fix unstable FlinkCatalogTest

fluss-common/src/main/java/com/alibaba/fluss/compression/FlussLZ4BlockInputStream.java, fluss-common/src/main/java/com/alibaba/fluss/compression/Lz4ArrowCompressionCodec.java
this ia a hotfix to fix the typo of the class name FlussLZ4BlockInputStream
=> [hotfix] Fix the typo of the class name FlussLZ4BlockInputStream

website/docs/table-design/table-types/pk-table/merge-engines/versioned.md
Linked issue: close #459
N/A
N/A
N/A
=> Add document about versioned merge engine

fluss-client/src/test/java/com/alibaba/fluss/client/admin/FlussAdminITCase.java, fluss-client/src/test/java/com/alibaba/fluss/client/write/RecordAccumulatorTest.java, fluss-client/src/test/java/com/alibaba/fluss/client/write/StickyStaticBucketAssignerTest.java, fluss-common/src/test/java/com/alibaba/fluss/cluster/ClusterTest.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorEventProcessor.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/ReplicaTestBase.java, fluss-server/src/test/java/com/alibaba/fluss/server/testutils/FlussClusterExtension.java
Linked issue: #524 
This pr is aims to fix the admin operation cannot be done error when `bootstrap server` config as one of `TabletServer`.  The reason for the issue is that the `NettyClient` has a connection cache, and the key for the cache is the `uid` of `ServerNode`, which is in parttern as `'cs' + id` or `'ts' + id`. In pr #456,  the UID of the `bootstrap server` was changed from `'ts--1'` to `'cs--1'`, which conflicted with our default `CoordinatorServer UID`, causing it to be identified as the same connection in the cache. The fix way is to change the default `CoordinatorServer UID` to `'cs-0'`.
=> [server] Fix admin operation cannot be done error when bootstrap server config as one of TabletServer

.github/workflows/ci-flink.yaml, fluss-connectors/fluss-connector-flink/pom.xml, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/sink/FlinkSink.java, fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/sink/FlinkSinkWriterTest.java, fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/sink/FlinkTableSinkITCase.java, fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/source/FlinkTableSourceFailOverITCase.java, fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/utils/FlinkConversionsTest.java, fluss-connectors/fluss-connector-flink/src/test/java/org/apache/flink/api/common/JobInfo.java, fluss-lakehouse/pom.xml, pom.xml
Linked issue: close #499
Support multiple versions of Flink including Flink 1.18, 1.19 and 1.20.
Placeholder class to resolve compatibility issues among Flink 1.18, 1.19 and 1.20.
- Local test with profile `flink-1.18` and `flink-1.19`.
```
mvn clean install -Pflink-1.18  -pl fluss-connectors/fluss-connector-flink
mvn clean install -Pflink-1.19  -pl fluss-connectors/fluss-connector-flink
```
- CI.
No.
No.
=> [connector] Support multiple versions of Flink

fluss-client/src/main/java/com/alibaba/fluss/client/metrics/WriterMetricGroup.java, fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/metrics/FlinkMetricsITCase.java, fluss-connectors/fluss-connector-flink/src/test/java/com/alibaba/fluss/connector/flink/sink/FlinkSinkWriterTest.java
Linked issue: close #549
The reason is the duration of `ProduceLog` RPC is too short and the `sendLatencyInMs` maybe small as 0 ms.
1. change the default `sendLatencyInMs` to `-1`
2. change the test comparison from `isGreaterThan(0)` to `isGreaterThanOrEqualTo(0)`
=> [tests] Fix FlinkSinkWriterTest.testSinkMetrics and FlinkMetricsITCase.testMetricsReport is unstable

fluss-client/src/main/java/com/alibaba/fluss/client/admin/Admin.java, fluss-client/src/main/java/com/alibaba/fluss/client/admin/FlussAdmin.java, fluss-client/src/main/java/com/alibaba/fluss/client/utils/ClientRpcMessageUtils.java, fluss-client/src/test/java/com/alibaba/fluss/client/admin/ClientToServerITCaseBase.java, fluss-client/src/test/java/com/alibaba/fluss/client/table/scanner/log/LogScannerITCase.java, fluss-common/src/main/java/com/alibaba/fluss/metadata/PartitionInfo.java, fluss-common/src/main/java/com/alibaba/fluss/metadata/PartitionSpec.java, fluss-common/src/main/java/com/alibaba/fluss/metadata/ResolvedPartitionSpec.java, fluss-common/src/main/java/com/alibaba/fluss/utils/PartitionUtils.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/catalog/FlinkCatalog.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/enumerator/FlinkSourceEnumerator.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/enumerator/initializer/BucketOffsetsRetrieverImpl.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/source/enumerator/initializer/OffsetsInitializer.java, fluss-connectors/fluss-connector-flink/src/main/java/com/alibaba/fluss/connector/flink/utils/PushdownUtils.java, fluss-lakehouse/fluss-lakehouse-paimon/src/main/java/com/alibaba/fluss/lakehouse/paimon/source/enumerator/FlinkSourceEnumerator.java, fluss-rpc/src/main/proto/FlussApi.proto, fluss-server/src/main/java/com/alibaba/fluss/server/RpcServiceBase.java, fluss-server/src/main/java/com/alibaba/fluss/server/utils/RpcMessageUtils.java
1. The `listPartition` API should return more information about partitions, so change from `partitionName` to `ResolvedPartitionSpec`. 
2. Change `listOffset(PhysicalTablePath ...)` to `listOffset(TablePath, partitionName ...)` to align with other partition related operations, such as `getLatestKvSnapshots`.
=> [client] Use partition spec in listPartitions

fluss-lakehouse/fluss-lakehouse-cli/src/main/java/com/alibaba/fluss/lakehouse/cli/FlussLakehouseCli.java
To pass datalake related args to run paimon tiering service in FlussLakehouseCli..
In #362 , we [miss-remove](https://github.com/alibaba/fluss/commit/7a4d71e36ad874969a74525545f7bc4e62ffd52b#diff-a8d1793ca21749941c4c05a5be11a5f5859be4738a48d4114422f289b5c9cc25L78) the datalake related args to run paimon tiering service.. This pr is to add them back..
=> [hotfix] Pass datalake related args run paimon tiering service in FlussLakehouseCli

fluss-kafka/src/main/java/com/alibaba/fluss/kafka/KafkaRequest.java, fluss-kafka/src/main/java/com/alibaba/fluss/kafka/KafkaRequestHandler.java, fluss-kafka/src/test/java/com/alibaba/fluss/kafka/KafkaRequestHandlerTest.java, fluss-kafka/src/test/java/com/alibaba/fluss/kafka/TestChannelHandlerContext.java
Linked issue: close https://github.com/alibaba/fluss/issues/545
Handle Kafka API_VERSIONS request
Tests completed
=> Handle Kafka API_VERSIONS request

fluss-common/src/test/java/com/alibaba/fluss/memory/TestingMemorySegmentPool.java, fluss-server/src/main/java/com/alibaba/fluss/server/utils/RpcGatewayManager.java
`do noting` should be `do nothing`.
=> [docs] Fix typo

fluss-server/src/main/java/com/alibaba/fluss/server/replica/IsrState.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/Replica.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/TestCoordinatorGateway.java, fluss-server/src/test/java/com/alibaba/fluss/server/log/remote/RemoteLogManagerTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/AdjustIsrTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/HighWatermarkPersistenceTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/ReplicaTestBase.java
Linked issue: #624 
This pr is aims to fix adjustIsr request re-send forever if encounter FencedLeaderEpochException error.
=> [server] Fix adjustIsr request re-send forever if encounter FencedLeaderEpochException error

fluss-server/src/main/java/com/alibaba/fluss/server/log/LogTablet.java, fluss-server/src/main/java/com/alibaba/fluss/server/log/remote/DefaultRemoteLogStorage.java
Remove unnecessary code in `DefaultRemoteLogStorage`
Remove redundant `CompletableFuture.get()` in `DefaultRemoteLogStorage`
=> [hotfix] remove redundant "wait" for CompletableFuture

fluss-server/src/main/java/com/alibaba/fluss/server/exception/CorruptIndexException.java, fluss-server/src/main/java/com/alibaba/fluss/server/log/AbstractIndex.java, fluss-server/src/main/java/com/alibaba/fluss/server/log/OffsetIndex.java, fluss-server/src/main/java/com/alibaba/fluss/server/log/TimeIndex.java, fluss-server/src/main/java/com/alibaba/fluss/server/log/remote/RemoteLogIndexCache.java, fluss-server/src/test/java/com/alibaba/fluss/server/log/TimeIndexTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/log/remote/RemoteLogIndexCacheTest.java
Linked issue: close #561
To fix the `CorruptIndexException` thrown by tablet server.
Catch `CorruptIndexException` of `RemoteLogIndexCache`, and delete the corrupt index.
`RemoteLogIndexCacheTest#testInitWithCorruptIndex`
=> [server] Fix CorruptIndexException for cached remote log index

fluss-server/src/main/java/com/alibaba/fluss/server/replica/Replica.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/ReplicaManager.java, fluss-server/src/test/java/com/alibaba/fluss/server/tablet/TabletServiceITCase.java
Improve the log message for becomeLeaderAndFollower to help debug
=> [hotfix] Improve log message for becomeLeaderAndFollower

fluss-client/src/main/java/com/alibaba/fluss/client/write/RecordAccumulator.java, fluss-client/src/test/java/com/alibaba/fluss/client/write/SenderTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/tablet/TestTabletServerGateway.java
Linked issue: #655 
This pr is aims to fix `Sender` maybe block forever error if `inflightBatchSize` in `IdempotenceManager` exceed `maxInflightRequestsPerBucket`.
In our current implementation, when the `inflightBatchSize` exceeds `maxInflightRequestsPerBucket`, no further requests can be sent. This is incorrect. We should allow the batch with the` smallest (first) batchSequence` to always be in a sendable state. This ensures that when the server can handle the retriable error, the client can recover.
=> [client] Fix Sender maybe block forever error if inflightBatchSize in IdempotenceManager exceed maxInflightRequestsPerBucket

fluss-common/src/main/java/com/alibaba/fluss/fs/utils/FileDownloadUtils.java, fluss-common/src/main/java/com/alibaba/fluss/utils/concurrent/FutureUtils.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/statemachine/ReplicaStateMachine.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/statemachine/TableBucketStateMachine.java, fluss-server/src/main/java/com/alibaba/fluss/server/kv/snapshot/KvTabletSnapshotTarget.java, fluss-server/src/main/java/com/alibaba/fluss/server/kv/snapshot/PeriodicSnapshotManager.java, fluss-server/src/main/java/com/alibaba/fluss/server/kv/snapshot/PlaceholderKvFileHandler.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/Replica.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/StopReplicaITCase.java, fluss-server/src/test/java/com/alibaba/fluss/server/kv/snapshot/RocksIncrementalSnapshotTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/kv/snapshot/TestingCompletedKvSnapshotCommitter.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/ReplicaTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/ReplicaTestBase.java
Linked issue: close #543
To fix the issue that  KvTablet can't restore when a snapshot is discarded
When the `KvFileHandler` is instance of `PlaceholderKvFileHandler`, shoudn't delete the file in method `discard`.  Flink Flink either doesn't delete for `PlaceholderState`.
The added code in `RocksIncrementalSnapshotTest#testIncrementalSnapshot` will try to discard new snapshot with `PlaceholderKvFileHandler` and restore from previous snapshot.
=> [server/kv] Fix KvTablet can't restore when a snapshot is discarded

fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorContext.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorEventProcessor.java, fluss-server/src/main/java/com/alibaba/fluss/server/zk/data/LeaderAndIsr.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/CoordinatorEventProcessorTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/tablet/TestTabletServerGateway.java
Linked issue: close #623 
To enable out of sync replica to clean logs that has been uploaded.
Send to all the followers instead the follower in isr the offset notification.
Added test `testNotifyOffsetsWithShrinkISR`
=> [coordinator] Send notifyOffset request to all followers instead of in-sync-followers

fluss-server/src/main/java/com/alibaba/fluss/server/replica/ReplicaManager.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/fetcher/ReplicaFetcherThread.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/fetcher/ReplicaFetcherThreadTest.java
Linked issue:  #674 
This pr is aims to fix the potential data loss issues when a `tabletServer` recovers from an unclean shutdown, the reason why there are a data loss issue is described in #674 .
Note that this is just an temporary solution, if we want to have a strong consistency guarantee, we should do as [KIP-101](https://cwiki.apache.org/confluence/display/KAFKA/KIP-101+-+Alter+Replication+Protocol+to+use+Leader+Epoch+rather+than+High+Watermark+for+Truncation) do, trace by:
#673
=> [server] Fix the potential data loss issues when a tabletServer recovers from an unclean shutdown

fluss-server/src/main/java/com/alibaba/fluss/server/replica/ReplicaManager.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/AdjustIsrITCase.java
Fix an error which causes all replicas to become follower and thus rebuild replicaFetcher.
Linked issue: close #620 
Remove  
`replicasBecomeFollower.add(replica);`
because we have added replica there:
```
if (replica.makeFollower(data)) {
replicasBecomeFollower.add(replica);
}
```
=> [hotfix] Fix an error which causes all replicas to become follower and rebuild replicaFetcher.

fluss-client/src/main/java/com/alibaba/fluss/client/metadata/MetadataUpdater.java, fluss-client/src/main/java/com/alibaba/fluss/client/table/scanner/log/LogFetcher.java, fluss-client/src/main/java/com/alibaba/fluss/client/utils/MetadataUtils.java, fluss-client/src/main/java/com/alibaba/fluss/client/write/Sender.java, fluss-client/src/test/java/com/alibaba/fluss/client/metadata/MetadataUpdaterTest.java, fluss-client/src/test/java/com/alibaba/fluss/client/metadata/TestingMetadataUpdater.java, fluss-client/src/test/java/com/alibaba/fluss/client/table/scanner/log/LogFetcherTest.java, fluss-client/src/test/java/com/alibaba/fluss/client/write/SenderTest.java, fluss-common/src/main/java/com/alibaba/fluss/exception/LeaderNotAvailableException.java, fluss-common/src/main/java/com/alibaba/fluss/exception/StaleMetadataException.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/protocol/Errors.java
Linked issue: close #605 
The pr will to try fix three problems:
1. no any alive tablet available to request metadata
2. the destinaion to send write batch can't be found in  metadata cache to cause NPE
3. the destinaion to fetcj can't be found in  metadata cache to cause NPE
Note the lookup, limit scan will also have the problem of NPE, but now, let's foucus on write and read.
1. some time, if client request metadata from a startingup tablet server, the tablet server will return empty metadata, we consider it as stale metadata and not to accept the metadata. Otherwise, we'll get into no alive tablet available to request metadata again
2. if the destinaion node can't be found in  metadata cache, invalid the metadata so that it can request metadata again to get the destinaion node …
=> [client] Consider empty tablet server metadata response as stale metadata & fix npe when detination to send and fetch can't be found in metadata

fluss-flink/fluss-flink-1.18/pom.xml, fluss-flink/fluss-flink-1.18/src/main/java/org/apache/flink/streaming/api/connector/sink2/SupportsPreWriteTopology.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/sink/FlinkSink.java
Linked issue: close #622.
`FlinkSink` implements `SupportsPreWriteTopology` instead of `WithPreWriteTopology`.
CI.
No.
No.
=> [flink] FlinkSink implements SupportsPreWriteTopology instead of WithPreWriteTopology

website/community/how-to-contribute/contribute-docs.md
Linked issue: close #536
Adds the new page for contribution to docs
A new page of .md format will be added for the contributors to get started with document-related contribution
=> [Website/Docs] Add "Contribute Documentation" for community usage

fluss-client/src/main/java/com/alibaba/fluss/client/table/scanner/log/LogScannerImpl.java, fluss-client/src/test/java/com/alibaba/fluss/client/table/FlussTableITCase.java
[client]Fix LogScannerImpl.poll always returns empty on the first request
Linked issue: close #683
com.alibaba.fluss.client.table.FlussTableITCase#testPollOnce
com.alibaba.fluss.client.table.FlussTableITCase#testPollOnceEmpty
=> [client]Fix LogScannerImpl.poll always returns empty on the first request

fluss-client/src/main/java/com/alibaba/fluss/client/metadata/MetadataUpdater.java, fluss-client/src/test/java/com/alibaba/fluss/client/metadata/MetadataUpdaterTest.java, fluss-common/src/main/java/com/alibaba/fluss/cluster/Cluster.java
Linked issue: close #699
Construct `bucketsForTable` with a new `ArrayList` instead of reusing the previous list which might be a `unmodifiableList`.  This leads to nested `unmodifiableList`.
Added `com.alibaba.fluss.client.metadata.MetadataUpdaterTest#testRebuildClusterNTimes` which can reproduce the StackOverflowError.
=> [client] Fix StackOverflowError after rebuilding Cluster N times

fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/catalog/FlinkCatalogITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/sink/FlinkTableSinkITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlinkTableSourceBatchITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlinkTableSourceFailOverITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlinkTableSourceITCase.java
Hotfix of test:
1. Fix testCreateDatabase return database out of order.
2. As a abstract class, FlinkTableSourceITCase's variable be visitable by child class
=> [hotfix][test] Fix testCreateDatabase any order.

fluss-client/src/main/java/com/alibaba/fluss/client/write/RecordAccumulator.java, fluss-client/src/test/java/com/alibaba/fluss/client/write/SenderTest.java
Linked issue: close #706 .
Currently, If we send multiple write batch requests. 
1. The first request is responsed with an retry RetriableException(such as TimeoutException), then it will be reEnqueue.
```java
Set<PhysicalTablePath> invalidMetadataTables = new HashSet<>();
if (canRetry(writeBatch, error.error())) {
if (!idempotenceManager.idempotenceEnabled()) {
reEnqueueBatch(writeBatch);
} else if (idempotenceManager.hasWriterId(writeBatch.writerId())) {
reEnqueueBatch(writeBatch);
}
```
2. The later requests are responsed with OutOfOrderSequenceException or UnknownWriterIdException. Then will reset writer id.
```java
synchronized void handleFailedBatch(
WriteBatch batch, Exception exception, boolean adjustSequenceNumbers) {
if (exception instanceof OutOfOrderSequenceException
|| …
```
=> [client] Fix sender in block when retry after resetting writer id.

website/docs/table-design/data-distribution/ttl.md, website/docs/table-design/table-types/pk-table/index.md
=> [docs]: update documentation for standardize "binlog" to "changelog"

fluss-server/src/main/java/com/alibaba/fluss/server/log/LogTablet.java
=> [log] Fix TabletServer cannot recover because OutOfOrderSequenceException by wrongly done takeSnapshot

fluss-server/src/main/java/com/alibaba/fluss/server/log/ListOffsetsParam.java, fluss-server/src/main/java/com/alibaba/fluss/server/log/LogTablet.java, fluss-server/src/main/java/com/alibaba/fluss/server/log/WriterStateEntry.java, fluss-server/src/main/java/com/alibaba/fluss/server/log/WriterStateManager.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/Replica.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/fetcher/LeaderEndpoint.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/fetcher/RemoteLeaderEndpoint.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/fetcher/ReplicaFetcherThread.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/fetcher/ReplicaFetcherThreadTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/fetcher/TestingLeaderEndpoint.java
Linked issue: close #704 
This pr is aims to address the issue where a `DuplicateSequenceException` or `OutOfOrderSequenceException` may occur when the follower fetches data from the leader for sync. The root cause of this problem lies in our current approach of updating the` follower's HW (HighWatermark)` before updating the `leader's HW`. This update mechanism may lead to the issues illustrated in the diagram below:
As in case 1, for example. In this scenario, when the leader, follower1, and follower2 are all offline, follower1 has written batch1 (WriterId=1, batchSequence=10), but the leader did not write this batch. When the tabletServer recover, follower2 is elected as the new leader. At this point, another writer, such as writer2 or writer3, quickly writes new batches and closes the …
=> [log] Follower fetch offset need truncate to leaderEndOffsetSnapshot if we found duplicated batch or out of sequence batch

fluss-server/src/main/java/com/alibaba/fluss/server/log/LogTablet.java, fluss-server/src/main/java/com/alibaba/fluss/server/log/WriterStateManager.java, fluss-server/src/main/java/com/alibaba/fluss/server/replica/ReplicaManager.java
This pr is aims to change `writerState` flush from async to sync while rolling log to avoid conflicts with the `writerState` flush during logTablet close.  
In the `LogTablet#roll()` method, the current implementation `writes the writerState` while holding the lock, but the `file flush operation` is performed outside the lock. However, this could potentially conflict with the `writerState write operation `in the `LogTablet#close() method`. Considering that the `writerState flush operation` itself is not very resource-intensive and the `roll()` method isn't called frequently, we consider change it to a sync flush approach.
=> [hotfix] Change writerState flush from async to sync while rolling log to avoid conflicts with the writerState flush during logTablet close

website/docs/apis/_category_.json, website/docs/apis/java-client.md, website/docusaurus.config.ts
Add documentation for Fluss admin client API
=> [docs] fluss admin client

fluss-server/src/test/java/com/alibaba/fluss/server/tablet/TabletServerFailOverITCase.java, fluss-server/src/test/java/com/alibaba/fluss/server/testutils/FlussClusterExtension.java
Linked issue: close #739
I found in `testIOExceptionShouldStopTabletServer`, it'll try to write data to a old tablet server. Then I found `newTabletServerClientForNode` will get the client for old server. We should use `Map` to keep `tabletServerInfos` instead of `List` which will cause it contains two different serverNodes with same tablet id
=> [hotfix] Fix unstable testIOExceptionShouldStopTabletServer

fluss-dist/src/main/resources/bin/coordinator-server.sh, fluss-dist/src/main/resources/bin/lakehouse.sh, fluss-dist/src/main/resources/bin/local-cluster.sh, fluss-dist/src/main/resources/bin/tablet-server.sh, website/docs/maintenance/tiered-storage/lakehouse-storage.md, website/docs/quickstart/flink.md
Linked issue: close #761
- Check for "starts with" instead of equality for dynamic properties argument, to support `-Dkey=value` (without space between `-D` option and its argument) in addition to `-D key=value` in CLI tooling.
- Adapt docs to use `-Dkey=value` instead of `-D key=value`
n/a
n/a
n/a
=> [Dist] Fix bug when passing dynamic properties to CLI tooling

fluss-server/src/main/java/com/alibaba/fluss/server/replica/Replica.java, fluss-server/src/test/java/com/alibaba/fluss/server/replica/delay/DelayedFetchLogTest.java
=> [server] Fix Tabletserver may run into deadlock status issue

fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/statemachine/ReplicaStateMachine.java, fluss-server/src/main/java/com/alibaba/fluss/server/zk/data/LeaderAndIsr.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/statemachine/ReplicaStateMachineTest.java
During complete #662, I mistake the mark leader as  `NO_LEADER` when the leader become offline in `ReplicaStatemachine` is only for unclean shutdown, so I keep the leader as same. But It may bring that the leader not in isr which will cause the leader change isr to empty array. 
This pr is to fix this.
When the leader of the bucket is offline,  set the leader to `-1` marked as `NO_LEADER` just like Kafka
Have verified in my env, but Let's add IT in #644 by the way.
=> [hotfix] Fix lead not in isr issue

fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/AutoPartitionManager.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorEventProcessor.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/AutoPartitionManagerTest.java
Linked issue: close #776 
Introduce jitter for day auto create partition
Before jitter, the metric look like:
After jitter, the metric looks more stable:
=> [server] Introduce jitter for day partition

fluss-common/src/main/java/com/alibaba/fluss/utils/PartitionUtils.java, fluss-common/src/test/java/com/alibaba/fluss/utils/PartitionUtilsTest.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/AutoPartitionManager.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorService.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/MetadataManager.java, fluss-server/src/main/java/com/alibaba/fluss/server/zk/ZooKeeperClient.java, fluss-server/src/main/java/com/alibaba/fluss/server/zk/data/TableRegistration.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/TableManagerITCase.java
Linked issue: close #712
This is a simple fix for #712 that during auto-partition creating it should first check if the table is dropped or re-created before creating partitions. This still don't guarantes the table id consist between the table node and partition node, because the table maybe re-created after the checking... But this should happen very rarely and is tracked in https://github.com/alibaba/fluss/issues/767.
=> [server] AutoPartitionManager shouldn't create partitions for dropped table

docker/docker-entrypoint.sh, fluss-dist/src/main/resources/bin/local-cluster.sh
Linked issue: close #618
`fluss-dist`
- Set `bind.listeners` as dynamic property in `local-cluster.sh` and choose random port to avoid port collision with `bind.listeners` option in `server.yaml` that is used by coordinator server
- Remove dead code
`docker`
Remove `bind.listeners` option from `server.yaml` in docker image to ensure backward compatibility with `[coordinator|tablet-server].host` option
n/a
n/a
n/a
=> Adapt tooling for `bind.listeners` config option

fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/source/FlussSource.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/source/FlussSourceBuilder.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlussSourceBuilderTest.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlussSourceITCase.java
Linked issue: close #804
Add a user-friendly field name-based projection API to FlussSourceBuilder while maintaining backward compatibility with the existing index-based approach.
- Added new `setProjectedFields(String[] fieldNames)` method to FlussSourceBuilder
- Added field name to index mapping in the build() method
- Added the projectedFieldNames List to store the requested field names
- Maintained backward compatibility with existing index-based API
- Modified comprehensive validation for field name existence
- Modified unit tests for the new field name-based API
- Fixed existing unit tests in FlussSourceBuilderTest for field name projection
- Fixed existing integration tests to use appropriate field names
This change extends the FlussSourceBuilder API by adding a more user-friendly …
=> [connector] Support projection pushdown via field names for fluss source

fluss-common/src/main/java/com/alibaba/fluss/config/ConfigOptions.java, fluss-kafka/src/main/java/com/alibaba/fluss/kafka/KafkaChannelInitializer.java, fluss-kafka/src/main/java/com/alibaba/fluss/kafka/KafkaCommandDecoder.java, fluss-kafka/src/main/java/com/alibaba/fluss/kafka/KafkaProtocolPlugin.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/NettyChannelInitializer.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/ClientChannelInitializer.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/server/FlussProtocolPlugin.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/server/NettyServer.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/server/ServerChannelInitializer.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/protocol/NetworkProtocolPlugin.java, website/docs/maintenance/configuration.md
Linked issue: close #820.
Support connection max idle time configuration for `KafkaProtocolPlugin`.
Introduce `kafka.connection.max-idle-time` to support connection max idle time configuration for `KafkaProtocolPlugin`.
No.
`NetworkProtocolPlugin` adds `setup(Configuration conf)` interface to setup network protoco plugin with the given configuration. 
Kafka section of `configuration.md` adds `kafka.connection.max-idle-time` config option.
=> [kafka] Support connection max idle time configuration for KafkaProtocolPlugin

fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/source/FlussSourceBuilder.java
Linked To: #569 
Add Comprehensive JavaDocs to FlussSourceBuilder
Documentation Improvements
- Added detailed JavaDoc comments to all public methods in FlussSourceBuilder
- Added parameter descriptions to clarify the purpose of each configuration option
- Added return value documentation for method chaining pattern
- Added exception information where applicable
- Documented required vs. optional parameters
- Clarified default behaviors for optional parameters
None
None
=> [connector] Javadocs fluss source builder

README.md, website/community/welcome.md
Add community communication channels to improve contributor engagement and coordination.
- Added Slack channel section with invitation link to the community page and readme.md
- Added Community Events section with details about the Fluss Contributors Call
N/A - Documentation change only
No impact on API or storage format.
Updates documentation to provide clear instructions for community participation channels.
=> [Document] Make slack and community call public

website/docs/install-deploy/deploying-distributed-cluster.md, website/docs/install-deploy/deploying-with-docker.md, website/docs/maintenance/observability/quickstart.md, website/docs/quickstart/flink.md
Linked issue: close #619
- Replaced `[coordinator|tablet-server].host` config option with `bind.listeners` in quickstart guides and "Deploying with Docker" guide
- Adapt "Deploying Distributed Cluster" to avoid port collision 
n/a
n/a
n/a
=> [Docs] Adapt docs for `bind.listeners` config option

fluss-client/src/main/java/com/alibaba/fluss/client/metrics/ScannerMetricGroup.java, fluss-client/src/main/java/com/alibaba/fluss/client/table/scanner/log/RemoteLogDownloader.java, fluss-client/src/test/java/com/alibaba/fluss/client/table/scanner/log/RemoteLogDownloaderTest.java
Linked issue: close #857
`RemoteLogDownloader` does not increment `remoteFetchBytesPerSecond` of `ScannerMetricGroup` at present, which causes that the value of `remoteFetchBytesPerSecond` metric is always zero.
`RemoteLogDownloader` should increment `remoteFetchBytesPerSecond` of `ScannerMetricGroup`.
`RemoteLogDownloaderTest#testPrefetchNum`.
No.
No.
=> [client] RemoteLogDownloader should increment remoteFetchBytesPerSecond of ScannerMetricGroup

fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/catalog/FlinkCatalogITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/metrics/FlinkMetricsITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/security/acl/FlinkAuthorizationITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/sink/FlinkTableSinkITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlinkTableSourceBatchITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlinkTableSourceFailOverITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlinkTableSourceITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/metrics/FlinkSourceReaderMetricsTest.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/testutils/FlinkRowAssertionsUtils.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/testutils/FlinkTestBase.java
Linked issue: close #868
To prevent Flink-core CI from failing randomly due to resource cleanup from one test iteration starting but not completing before another test iteration accesses the same resources, causing the test case to run indefinitely, eventually causing the CI pipeline to timeout.
- Proper cleanup of resources after each test using `AbstractTestBase` MiniClusterExtension using cleanupRunningJobs
- Explicitly wait for bucket snapshots to complete before collecting results in `testPrefixLookupWithCondition`
- Created a separate utility class `FlinkRowAssertionsUtils` for assertion method, moved away from `FlinkTestBase` to avoid duplicate code, & Improved error handling and closure for the same.
- Removed extensibility of `FlinkTestBase` from `FlinkMetricsITCase`, manually …
=> [Connector] Resource cleanup via AfterEach Extending AbstractStreamBase

LICENSE, fluss-common/src/main/java/com/alibaba/fluss/exception/RetriableAuthenticationException.java, fluss-common/src/main/java/com/alibaba/fluss/security/auth/ClientAuthenticator.java, fluss-common/src/main/java/com/alibaba/fluss/security/auth/ServerAuthenticator.java, fluss-common/src/main/java/com/alibaba/fluss/utils/ExponentialBackoff.java, fluss-common/src/test/java/com/alibaba/fluss/utils/ExponentialBackoffTest.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/client/ServerConnection.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/netty/server/NettyServerHandler.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/protocol/Errors.java, fluss-rpc/src/test/java/com/alibaba/fluss/rpc/netty/authenticate/AuthenticationTest.java, fluss-rpc/src/test/java/com/alibaba/fluss/rpc/netty/authenticate/MutualAuthenticationPlugin.java
Linked issue: close #844 
com.alibaba.fluss.rpc.netty.authenticate.AuthenticationTest#testRetirableAuthenticateException
=> [server] Add retriable authentication exception.

README.md
Currently, the ci-badge is looking for CI status for all branches combined, causing any feature/experimental branch to fail, marking the entire CI badge as Fail
Add & Set the branch parameter to the main branch for the CI badge.
None
None
None
=> [Website] Check only main branch for ci-badge

fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/catalog/FlinkCatalogITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/sink/FlinkTableSinkITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlinkTableSourceBatchITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlinkTableSourceITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlussSourceITCase.java
The variable in abstract class (such as FlinkTableSinkITCase) in private now, its subclass can not use it.
=> [hotfix] Mark abstract itcase's variable as protected.

fluss-rpc/src/main/java/com/alibaba/fluss/rpc/gateway/CoordinatorGateway.java, fluss-rpc/src/main/java/com/alibaba/fluss/rpc/protocol/ApiKeys.java, fluss-rpc/src/main/proto/FlussApi.proto, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorEventProcessor.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorServer.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorService.java, fluss-server/src/main/java/com/alibaba/fluss/server/utils/ServerRpcMessageUtils.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/LakeTieringHeartbeatITCase.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/TestCoordinatorGateway.java
Linked issue: close #432 
Introduce RPC request for laketiering heartbeat request:
LakeTieringHeartbeatRequest:
```
message LakeTieringHeartbeatRequest {
repeated PbHeartbeatReqForTable tiering_tables = 2;
repeated PbHeartbeatReqForTable finished_tables = 3;
repeated PbHeartbeatReqForTable failed_tables = 4;
// whether to request a table
optional bool request_table = 5;
}
message PbHeartbeatReqForTable {
// the coordinator epoch when the table has been assigned to be tiering service
required int64 table_id = 1;
required int32 coordinator_epoch = 2;
required int32 tiering_epoch = 3;
}
```
LakeTieringHeartbeatResponse:
```
message PbHeartbeatReqForTable {
required int64 table_id = 1;
// the coordinator epoch when the table is assigned to be tiering service
required int32 coordinator_epoch = …
```
=> Add HeartBeat RPC in Servers for Tiering Services

fluss-common/src/main/java/com/alibaba/fluss/memory/LazyMemorySegmentPool.java, fluss-common/src/test/java/com/alibaba/fluss/memory/LazyMemorySegmentPoolTest.java
When `public void returnAll(List<MemorySegment> memory) {`
returns memory segment, it polls the first waiter and wakes it up in Deque to judge if freePages is less than requiredPages. If not, this waiter calls await() again and will no longer be waked up. This should cause memory allocation stuck and can't recover.
=> [bugfix] Fix a bug which makes memory allocation stuck

fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/source/FlinkSource.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/source/FlinkTableSource.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/source/FlussSource.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/source/enumerator/FlinkSourceEnumerator.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/utils/PushdownUtils.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/FlinkTableSourceITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/enumerator/FlinkSourceEnumeratorTest.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/testutils/FlinkTestBase.java, fluss-lakehouse/fluss-lakehouse-paimon/src/test/java/com/alibaba/fluss/lakehouse/paimon/flink/LakeTableEnumeratorTest.java
[flink]
Purpose
Support partition pushdown(only equals) in Flink connector
Linked issue: close https://github.com/alibaba/fluss/issues/196
Tests
com.alibaba.fluss.connector.flink.source.FlinkTableSourceITCase#testStreamingReadSinglePartitionPushDown
com.alibaba.fluss.connector.flink.source.FlinkTableSourceITCase#testStreamingReadMultiPartitionPushDown
API and Format
no
Documentation
no
=> [flink]Support partition pushdown(only equals) in Flink connector

fluss-common/src/main/java/com/alibaba/fluss/lakehouse/committer/CommitterInitContext.java, fluss-common/src/main/java/com/alibaba/fluss/lakehouse/committer/LakeCommitter.java, fluss-common/src/main/java/com/alibaba/fluss/lakehouse/lakestorage/LakeStorage.java, fluss-common/src/main/java/com/alibaba/fluss/lakehouse/writer/LakeTieringFactory.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/PaimonLakeStorage.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/FlussRecordAsPaimonRow.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonCatalogProvider.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonCommittable.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonCommittableSerializer.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeCommitter.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeTieringFactory.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeWriter.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonWriteResult.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonWriteResultSerializer.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/RecordWriter.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/append/AppendOnlyWriter.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/mergetree/MergeTreeWriter.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/utils/PaimonConversions.java, fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/tiering/FlussRecordAsPaimonRowTest.java, fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/tiering/PaimonTieringTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/lakehouse/TestingPaimonStoragePlugin.java
Linked issue: close #438 
- Implement `PaimonLakeTieringFactory` to create `PaimonLakeWriter` and `PaimonLakeCommiter`
- `PaimonLakeWriter`/`PaimonLakeCommiter` use Paimon sdk to write/commit to paimon
Note: 
- this pr use Paimon sdk to write row by row. It left to convert arrow to parquet in the future pr. In the future, we can call `TableWrite#writeBundle(BinaryRow partition, int bucket, BundleRecords bundle)` to write `ArrowBatch` of Fluss to paimon directly.
- this pr only consider one signle partition, let's consider mutiple partition in #953 
`PaimonTieringTest` to verify the logic of `PaimonLakeWriter`/`PaimonLakeCommiter`
=> [lake/paimon] Support paimon tiering factory

fluss-client/src/main/java/com/alibaba/fluss/client/table/scanner/log/LogFetchCollector.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/security/acl/FlinkAuthorizationITCase.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/source/testutils/FlinkRowAssertionsUtils.java
FLINK - CI Times out randomly due to Job failure/resource clean up issue.
Linked issue: close #934 
> LogFetchCollector Changes:
Before: When we got an “unknown table or bucket” error, we would just log a warning and update metadata. Then the system would keep trying to fetch from that same non-existent bucket over and over again.
After: Now when we get an `UNKNOWN_TABLE_OR_BUCKET_EXCEPTION` error, we first check if the bucket is still assigned in our scanner status. If it is, we log the warning AND immediately remove that bucket from the scanner status so we stop trying to fetch from it. If the bucket was already unassigned, we just log a debug message instead of a warning to reduce noise.
>  AssertResultsIgnoreOrder utility method that reads results from Flink job iterators:
Before: The …
=> [Flink] Change logfetchercollector warning and timeout closableiterator

website/src/pages/index.module.css, website/src/pages/index.tsx
Linked issue: n/a
The button group on the landing page (quick start, github, slack) is not responsive and overflows on small screen resolutions (e.g., on mobile phones).
Example on an iPhone 12 Pro (note that the quick start and Slack button are cut off on the left and right hand side, respectively).
- Make button fixed and same size
- Wrap when display resolution gets too small
- Remove redundant code
**Examples**
iPhone 12 Pro
600x750
n/a
n/a
n/a
=> [Website] Fix responsiveness of button group on landing page

fluss-lake/fluss-lake-paimon/pom.xml, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/FlussRecordAsPaimonRow.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeWriter.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/RecordWriter.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/append/AppendOnlyWriter.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/mergetree/MergeTreeWriter.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/utils/PaimonConversions.java, fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/tiering/FlussRecordAsPaimonRowTest.java, fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/tiering/PaimonTieringTest.java
Linked issue: close #953
Implement multi-partition support for Paimon lake tiering to enable tables with multiple partition fields (e.g., region=us-east/year=2024/month=01) instead of only single partition support.
- Enhanced partition conversion logic: Added toPaimonPartitionBinaryRow() method in PaimonConversions to parse multi-partition strings and create correctly sized BinaryRow objects
- Redesigned row adapter: Modified FlussRecordAsPaimonRow to support dynamic field layout with business + partition + system fields, extracting partition values from metadata instead of record data
- Updated writer infrastructure: Enhanced RecordWriter, AppendOnlyWriter, MergeTreeWriter, and PaimonLakeWriter to pass partition schema information and handle multi-partition field mapping
- Fixed field …
=> [Lake/paimon] Tiering for multi partition paimon table

fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/utils/PojoToRowConverter.java, fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/utils/PojoToRowConverterTest.java
This PR is a minor improvement for PojoToRowConverterTest.
Use ordered set in PojoToRowConverter to make test stable, because the key order of HashSet is not predictable which make s the test unstable especially when we use different JDK versions.
covered by PojoToRowConverterTest
no
no
=> [flink] Use ordered set in PojoToRowConverter to make test stable

fluss-client/src/main/java/com/alibaba/fluss/client/write/DynamicWriteBatchSizeEstimator.java, fluss-client/src/test/java/com/alibaba/fluss/client/write/DynamicWriteBatchSizeEstimatorTest.java
This is a hotfix to adjust the writeBatch estimate logic to avoid buffer size always tending to decrease
=> [hotfix] Adjust the writeBatch estimate logic to avoid buffer size always tending to decrease

website/docs/install-deploy/deploying-with-docker.md
`docker run` and `docker compose` use different configuration options. To make it easier for users to follow the guides, make them consistent.
=> [Hotfix][Docs] Fix inconsistent configuration options in "Deploy with Docker"

fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/source/TieringSourceReader.java, fluss-flink/fluss-flink-tiering/src/main/java/com/alibaba/fluss/flink/tiering/FlussLakeTieringEntrypoint.java
=> [hotfix] Always use full restart strategy for tiering service to avoid table can't be committed to lake

fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/FlussRecordAsPaimonRow.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/RecordWriter.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/append/AppendOnlyWriter.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/mergetree/MergeTreeWriter.java, fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/tiering/FlussRecordAsPaimonRowTest.java
=> [lake/paimon] Fix than tiering service for paimon missed timestampNtz support

website/docs/streaming-lakehouse/integrate-data-lakes/paimon.md
Linked issue: close #448
Update paimon integration docs in lakehouse section
=> [lake/docs] Update paimon integration docs in lakehouse section

fluss-common/src/main/java/com/alibaba/fluss/lake/writer/WriterInitContext.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/source/TieringSplitReader.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/source/TieringWriterInitContext.java, fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/tiering/PaimonTieringTest.java
Use the schema in Fluss as the single source of truth for the lake writers to avoid any inconsistency.
Moreover, we sometimes need the Fluss schema to pick the correct field writers when creating lake writer. For example, currently the LocalZonedTimestampType and TimestampType type in Fluss map to the same Arrow type: 
https://github.com/alibaba/fluss/blob/main/fluss-common/src/main/java/com/alibaba/fluss/utils/ArrowUtils.java#L476
https://github.com/alibaba/fluss/blob/main/fluss-common/src/main/java/com/alibaba/fluss/utils/ArrowUtils.java#L489
When we tier the table to a data lake with Arrow schema, we are not able to choose the appropriate type of filed writers.
Add the schema in Fluss to WriterInitContext.
n/a
n/a
n/a
=> [connector] pass Fluss schema to lake writer

fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/flink/FlinkUnionReadLogTableITCase.java, fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/flink/FlinkUnionReadPrimaryKeyTableITCase.java, fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/flink/FlinkUnionReadTestBase.java, fluss-lake/fluss-lake-paimon/src/test/java/com/alibaba/fluss/lake/paimon/testutils/FlinkPaimonTieringTestBase.java
Linked issue: close [#1127](https://github.com/alibaba/fluss/issues/1127)
=> Fulltype unionread test

website/docs/table-design/table-types/pk-table/merge-engines/default.md
https://alibaba.github.io/fluss-docs/docs/table-design/table-types/pk-table/merge-engines/default/
The deletion operation requires the equivalence condition of the primary key
1. Before executing the update operation, add a statement to switch to batch mode execution, otherwise an error will be reported: org.apache.flink.table.api.TableException: UPDATE statement is not supported for streaming mode now.
2. Delete from T WHERE k>2 statement; Change to DELETE FROM T WHERE k=2;
3. SELECT * FROM T; Change to SELECT * FROM T WHERE k=2;
4. Change the result output of the query statement
**Does this change affect API or storage format**:
本次修改仅调整了 SQL 查询语句和表结构定义，不影响对外 API 或数据存储格式。
**Does this change …
=> [doc]The deletion operation requires the equivalence condition of the primary key

fluss-flink/fluss-flink-common/src/test/java/com/alibaba/fluss/flink/utils/FlinkTestBase.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/MetadataManager.java, fluss-server/src/main/java/com/alibaba/fluss/server/zk/ZooKeeperClient.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/CoordinatorEventProcessorTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/TableManagerTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/event/watcher/TableChangeWatcherTest.java, fluss-server/src/test/java/com/alibaba/fluss/server/zk/ZooKeeperClientTest.java
=> [server] Fix zk partition residual when using dynamic partition

website/docs/engine-flink/reads.md
Remove 'testcatalog'. 'testdb' from the ddl statement
See the picture for details：
1、Remove testcatalog.testdb. from the streaming section
2、Maintain consistency in the ddl statements for document streaming read and batch read
=> [doc]Remove 'testcatalog'. 'testdb' from the ddl statement

website/docs/table-design/table-types/log-table.md
Fix the issue of mismatched DDL and DQL column names in the context, ensuring that the query statement is consistent with the table structure definition.
https://alibaba.github.io/fluss-docs/docs/table-design/table-types/log-table/
The DDL and DQL column names in the context do not match:
1. Added a 'timestamp' column in the DDL definition to ensure that the table structure includes a timestamp field.
2. Modified the 'SELECT' statement to explicitly specify the column names for the query:
-Original statement: ` SELECT * FROM log_table WHERE timestamp>'2023-01-01'; `
-New statement: ` SELECT order_i, item_id FROM log_table WHERE timestamp>'2023-01-01'; `
3. Optimized the description of query …
=> [doc]The DDL and DQL column names in the context do not match

fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeCommitter.java, fluss-lake/fluss-lake-paimon/src/main/java/com/alibaba/fluss/lake/paimon/tiering/PaimonLakeWriter.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/MetadataManager.java
Small improvement to add a exception root cause when trying to debug why the lakewriter or committer fail.
=> Add exception in throwable in lake writer & committer

fluss-common/src/main/java/com/alibaba/fluss/lake/lakestorage/LakeStoragePluginSetUp.java, fluss-common/src/main/java/com/alibaba/fluss/lake/lakestorage/PluginLakeStorageWrapper.java, fluss-common/src/test/java/com/alibaba/fluss/lake/lakestorage/LakeStorageTest.java, fluss-flink/fluss-flink-common/src/main/java/com/alibaba/fluss/flink/tiering/LakeTieringJobBuilder.java, fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/CoordinatorServer.java
Linked issue: close #1168
Use plugin classloader as thread current classloader, and ensure LakeStoragePlugin uses the plugin classloader for all operations
com.alibaba.fluss.lake.lakestorage.LakeStorageTest
=> [lake] Ensure LakeStoragePlugin uses the plugin classloader for all operations

fluss-server/src/main/java/com/alibaba/fluss/server/coordinator/AutoPartitionManager.java, fluss-server/src/test/java/com/alibaba/fluss/server/coordinator/AutoPartitionManagerTest.java
=> [server] Optimize auto drop partition perfomance

website/community/how-to-contribute/bug-reports-feature-requests.md
Linked issue: close #1209
Improve documentation for bug reports and feature requests 
- Added bug report and feature request page for a better user experience
- Added a new file bug-reports-feature-requests.md
Yes - improves existing documentation structure and content
=> [website] create a seperate page for bug report & feature request

fluss-common/src/main/java/com/alibaba/fluss/row/TimestampNtz.java
Potential fix for [https://github.com/apache/fluss/security/code-scanning/5](https://github.com/apache/fluss/security/code-scanning/5)
To resolve the issue, we can ensure that `time` is explicitly widened to a `long` type before adding `MILLIS_PER_DAY`. This avoids implicit narrowing when the result is assigned back to `time`. Alternatively, we can change the type of `time` itself to `long` to ensure safe arithmetic operations throughout the method. Changing `time` to `long` is the more robust solution, as it aligns with the type of `MILLIS_PER_DAY` and avoids potential issues in other operations involving `time`.
**Steps to fix:**
1. Change the declaration of `time` on line 119 from `int` to `long`.
2. Update any subsequent uses of `time` in the method to accommodate the new type.
This …
=> Potential fix for code scanning alert no. 5: Implicit narrowing conversion in compound assignment

.github/workflows/stage.sh, fluss-dist/pom.xml, fluss-dist/src/main/assemblies/plugins.xml, fluss-lake/fluss-lake-iceberg/pom.xml, fluss-lake/fluss-lake-iceberg/src/main/java/com/alibaba/fluss/lake/iceberg/IcebergLakeStorage.java, fluss-lake/fluss-lake-iceberg/src/main/java/com/alibaba/fluss/lake/iceberg/IcebergLakeStoragePlugin.java, fluss-lake/fluss-lake-iceberg/src/main/resources/META-INF/NOTICE, fluss-lake/fluss-lake-iceberg/src/main/resources/META-INF/services/com.alibaba.fluss.lake.lakestorage.LakeStoragePlugin, fluss-lake/fluss-lake-iceberg/src/test/resources/log4j2-test.properties, fluss-lake/fluss-lake-iceberg/src/test/resources/org.junit.jupiter.api.extension.Extension, fluss-lake/fluss-lake-paimon/pom.xml, fluss-lake/pom.xml, fluss-test-coverage/pom.xml
=> set up fluss-lake-iceberg module and IcebergLakeStorage

fluss-client/src/main/java/com/alibaba/fluss/client/table/scanner/log/LogFetchCollector.java
Currently, When a `LogOffsetOutOfRangeException` is thrown in `LogFetchCollector`, the current error message only provides the default exception defined in `Errors`: "The log offset is out of range", which is insufficient for troubleshooting.
=> [hotfix] Optimize the error msg when throwing LogOffsetOutOfRangeException

fluss-filesystems/fluss-fs-oss/pom.xml
Linked issue: close #1322 
Exclude `com.alibaba.fluss.fs.hdfs.HadoopFsPlugin` from META-INF in the `fluss-fs-oss plugin` to resolve the `ClassNotFoundException` caused by missing Hadoop dependencies.
For `fluss-fs-oss-0.8-SNAPSHOT.jar`
Before:
``` 
com.alibaba.fluss.fs.oss.OSSFileSystemPlugin
com.alibaba.fluss.fs.hdfs.HadoopFsPlugin
```
After fix :
```
com.alibaba.fluss.fs.oss.OSSFileSystemPlugin
```
=> [filesystem] Exclude com.alibaba.fluss.fs.hdfs.HadoopFsPlugin from META-INF for fluss-fs-oss plugin

website/docs/quickstart/flink.md
Remove the extra period at the end of the sentence
1.Remove the extra period at the end of the sentence in flink.md
=> [doc]Remove the extra period at the end of the sentence

website/docs/concepts/architecture.md
fix typos, formatting and consistency in architecture.md
1、.…the Coordinator Server ensures…→  CoordinatorServer
2、For Log Tables which only supports appends  →  which only support appends
3、…clients/sdks support streaming reads/writes, batch read/writes, DDL and point queries.
• “sdks” → SDKs
• batch read/writes  →   batch reads/writes
=> [doc] fix typos, formatting and consistency in architecture.md

website/docs/quickstart/security.md
The SQL keywords are not consistent in case. It is recommended to use uppercase letters uniformly
1.The SQL keywords are not consistent in case. It is recommended to use uppercase letters uniformly
=> [doc]The SQL keywords are not consistent in case. It is recommended to use uppercase letters uniformly

website/docs/table-design/table-types/pk-table/index.md
Fix: Correct column specification in T table INSERT statements
https://fluss.apache.org/docs/table-design/table-types/pk-table/#lookup
1. Background: The original INSERT statements specified only partial columns (k, v1), but the VALUES clause contained more data points that didn't match the actual column structure of table T. This could lead to logical errors in data insertion.
﻿
2. Changes made: Added missing columns to the INSERT INTO statements. Based on the complete column definition of table T (assumed to be k INT, v1 DOUBLE, v2 STRING), all columns (k, v1, v2) are now explicitly specified to ensure full-column insertion that matches the table structure and business requirements.
﻿
3. …
=> [docs] Fix: Correct column specification in T table INSERT statements

website/docs/install-deploy/deploying-local-cluster.md
fix typos, format in deploying-local-cluster.md
1、.…start to setup the system… → …start to set up the system（动词短语用set up）
2、 …only support Flink Sql Client… → Flink SQL Client（SQL大写）
3、…More details please refer to Flink Getting started → More details please refer to Flink Getting Started（Flink Getting Started标题大写）
=> [doc] fix typos, format in deploying-local-cluster.md

.github/workflows/ci-template.yaml, .github/workflows/ci.yaml, .github/workflows/daily.yaml, .github/workflows/license-check.yml, .github/workflows/nightly.yaml, pom.xml
=> [build] Upgrade JDK compile version as 11 

fluss-common/src/main/java/com/alibaba/fluss/metrics/groups/AbstractMetricGroup.java
Linked issue: https://github.com/apache/fluss/issues/1362
Optimize the createLogicalScope method by adding empty groupName checks to avoid unnecessary delimiter concatenation.
=> [hotfix] Optimize the createLogicalScope method by adding empty groupName checks to avoid unnecessary delimiter concatenation.

fluss-server/src/main/java/com/alibaba/fluss/server/log/AbstractIndex.java, fluss-server/src/main/java/com/alibaba/fluss/server/log/OffsetIndex.java, fluss-server/src/main/java/com/alibaba/fluss/server/log/TimeIndex.java, fluss-server/src/test/java/com/alibaba/fluss/server/log/AbstractIndexTest.java
Linked issue: #1377 
This pr is aims to fix the error mentioned in #1377.
=> [server] force unmap mmap file on linux when call AbstractIndex.resize()

fluss-lake/fluss-lake-iceberg/src/main/java/org/apache/fluss/lake/iceberg/tiering/IcebergLakeCommitter.java
Linked issue: close #1580 
FIx unstable Iceberg TieringITCase
Note such error log 
```
com.alibaba.fluss.flink.tiering.source.enumerator.TieringSourceEnumerator [] - Tiering table 1 is failed, fail reason is java.lang.IllegalStateException: The current Fluss's lake snapshot 5402285830333994804 is less than lake actual snapshot 8732241012020816263 committed by Fluss for table: {tablePath=fluss.logTable, tableId=1}, missing snapshot: CommittedLakeSnapshot{lakeSnapshotId=8732241012020816263, logEndOffsets={(null,0)=6}, partitionNameById={}}.
```
But actaully,  snapshot `8732241012020816263` is the parent of snapshot `5402285830333994804`  which means snapshot `8732241012020816263` is actally an older snapshot than snapshot `5402285830333994804`.
So, not compare with icberge snapshot id since …
=> [hotfix] Fix unstable test IcebergTieringITCase

fluss-lake/fluss-lake-paimon/src/main/java/org/apache/fluss/lake/paimon/source/PaimonSortedRecordReader.java, fluss-lake/fluss-lake-paimon/src/test/java/org/apache/fluss/lake/paimon/source/PaimonSourceTestBase.java
Linked issue: close #1648
Add paimon privilege test.
=> [lake] Avoid cast to KeyValueFileStore to get keyComparator in paimon

fluss-protogen/fluss-protogen-generator/src/main/java/org/apache/fluss/protogen/generator/generator/ProtobufMessage.java, fluss-protogen/fluss-protogen-generator/src/main/java/org/apache/fluss/protogen/generator/generator/RecordsFieldFinder.java, fluss-protogen/fluss-protogen-tests/pom.xml, fluss-protogen/fluss-protogen-tests/src/main/proto/circular_reference.proto, fluss-protogen/fluss-protogen-tests/src/test/java/org/apache/fluss/protogen/tests/RecordsFieldFinderTest.java
Linked issue: close #1281
Introduce a set to track visited message types to avoid infinite recursion in RecordsFieldFinder
=> [bug fix] Avoid infinite recursion in RecordsFieldFinder

fluss-server/src/main/java/org/apache/fluss/server/log/LogTablet.java, fluss-server/src/main/java/org/apache/fluss/server/log/WriterAppendInfo.java, fluss-server/src/test/java/org/apache/fluss/server/log/WriterStateManagerTest.java, fluss-server/src/test/java/org/apache/fluss/server/replica/ReplicaTest.java, fluss-server/src/test/java/org/apache/fluss/server/replica/ReplicaTestBase.java, fluss-server/src/test/java/org/apache/fluss/server/replica/fetcher/ReplicaFetcherThreadTest.java
=> [server] Fix ReplicaFetcherThread keeps throwing OutOfOrderSequenceException because of writer id expire

website/docs/maintenance/operations/racks.md, website/docs/maintenance/operations/upgrade-notes-0.8.md, website/docs/maintenance/operations/upgrade-notes-0.9.md, website/src/css/custom.css
This adds the Upgrade Notes page the new version (0.7 -> 0.8).
These upgrade notes discuss important aspects, such as configuration, behavior, or dependencies, that changed between Fluss 0.7 and Fluss 0.8. We provide these notes to users for users planning to upgrade Fluss version to 0.8.
Linked issue: close #1693
- This is only a draft of upgrade notes of 0.8, more items should be added later
- There is a version number in the URL slug for the upgrade notes (e.g., `http://fluss.apache.org/docs/next/maintenance/operations/upgrade-notes-0.8/`), this is useful when the release announcement blog link the upgrade note, to have a static content of this version of upgrade notes. 
- Added another upgrade notes for the v0.9 as an example when we rolling versions, and the front-matter support to …
=> [docs] Add Upgrade Notes for 0.8

fluss-server/src/main/java/org/apache/fluss/server/log/remote/RemoteLogIndexCache.java
Currently, when an error occurs while loading an index file, it is difficult to determine which table the file belongs to.
```
2025-09-17 10:36:20,114 INFO  com.alibaba.fluss.server.log.remote.RemoteLogIndexCache      [] - Error occurred while loading the stored index file /mnt/fluss/data/0/remote-log-index-cache/77878665_6c45b095-35dc-4202-8878-02e9121d92de.timeindex
com.alibaba.fluss.server.exception.CorruptIndexException: Corrupt time index found, time index file (/mnt/fluss/data/0/remote-log-index-cache/77878665_6c45b095-35dc-4202-8878-02e9121d92de.timeindex) has non-zero size but the last timestamp is 0 which is less than the first timestamp 1758020356382
at com.alibaba.fluss.server.log.TimeIndex.lambda$sanityCheck$0(TimeIndex.java:105) ~[fluss-server-0.8-SNAPSHOT.jar:0.8-SNAPSHOT] …
```
=> [hotfix] Add bucket info for error info while loading the stored index file

fluss-rpc/src/main/java/org/apache/fluss/rpc/netty/server/NettyServerHandler.java
Add debug log for `NettyServerHandler` to trace the request process time. This is very useful when there is a bottleneck in cluster network request processing, as it can quickly identify slow requests.
=> [hotfix] Add debug log for NettyServerHandler to trace the request process time

fluss-rpc/src/main/java/org/apache/fluss/rpc/netty/client/ServerConnection.java, fluss-rpc/src/test/java/org/apache/fluss/rpc/netty/client/NettyClientTest.java, fluss-rpc/src/test/java/org/apache/fluss/rpc/netty/client/ServerConnectionTest.java
Linked issue: close #1721 
Fix serverConnection that has already been set to disconnected is still processing requests error.
=> [common] Fix serverConnection that has already been set to disconnected is still processing requests error

fluss-common/src/main/java/org/apache/fluss/cluster/Cluster.java, fluss-common/src/test/java/org/apache/fluss/cluster/ClusterTest.java
Linked issue: close #1718 
`Cluster#getRandomTabletServer()` does not truly randomly retrieve a `TabletServer`. The current implementation of `getRandomTabletServer` always retrieves the first element from the map iterator, which results in consistently selecting `TabletServer-0`.
```java
public ServerNode getRandomTabletServer() {
// TODO this method need to get one tablet server according to the load.
List<ServerNode> serverNodes = new ArrayList<>(aliveTabletServersById.values());
return !serverNodes.isEmpty() ? serverNodes.get(0) : null;
}
```
This pr is aims to change `Cluster#getRandomTabletServer()` to really random retrieve `tabletServer`.
=> [common] Change Cluster#getRandomTabletServer() to really random retrieve tabletServer

fluss-flink/fluss-flink-1.18/src/main/java/org/apache/flink/table/catalog/CatalogBaseTable.java, fluss-flink/fluss-flink-1.18/src/main/java/org/apache/flink/table/catalog/CatalogMaterializedTable.java, fluss-flink/fluss-flink-1.18/src/main/java/org/apache/flink/table/catalog/IntervalFreshness.java, fluss-flink/fluss-flink-1.18/src/main/java/org/apache/flink/table/catalog/TableChange.java, fluss-flink/fluss-flink-1.19/src/main/java/org/apache/flink/table/catalog/CatalogBaseTable.java, fluss-flink/fluss-flink-1.19/src/main/java/org/apache/flink/table/catalog/CatalogMaterializedTable.java, fluss-flink/fluss-flink-1.19/src/main/java/org/apache/flink/table/catalog/IntervalFreshness.java, fluss-flink/fluss-flink-1.19/src/main/java/org/apache/flink/table/catalog/TableChange.java, fluss-flink/fluss-flink-1.20/pom.xml, fluss-flink/fluss-flink-1.20/src/test/java/org/apache/fluss/flink/catalog/Flink120MaterializedTableITCase.java, fluss-flink/fluss-flink-2.1/pom.xml, fluss-flink/fluss-flink-2.1/src/test/java/org/apache/fluss/flink/catalog/Flink21MaterializedTableITCase.java, fluss-flink/fluss-flink-common/pom.xml, fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/FlinkConnectorOptions.java, fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/catalog/FlinkCatalog.java, fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/catalog/FlinkCatalogOptions.java, fluss-flink/fluss-flink-common/src/main/java/org/apache/fluss/flink/utils/FlinkConversions.java, fluss-flink/fluss-flink-common/src/test/java/org/apache/fluss/flink/catalog/FlinkCatalogTest.java, fluss-flink/fluss-flink-common/src/test/java/org/apache/fluss/flink/catalog/MaterializedTableITCase.java, fluss-flink/fluss-flink-common/src/test/java/org/apache/fluss/flink/utils/CatalogTableTestUtils.java, fluss-flink/fluss-flink-common/src/test/java/org/apache/fluss/flink/utils/FlinkConversionsTest.java, fluss-test-coverage/pom.xml
Linked issue: close #861 
- `FlinkCatalog` supports create/get/drop materialized table
- Since materialized table is a concept introduced by Flink, we convert it into a common Fluss table, introduce relevant options, and save them in `customProperties` to identify it as a materialized table. This is also the current implementation method of Paimon
- Since Paimon already supports materialized tables and has introduced related options, the options introduced in Fluss are aligned with those in Paimon. Since Fluss supports tiering tables to Paimon, when a Fluss materialized table is sync to Paimon, it should also be a Paimon materialized table, so the option names of the two are kept consistent. Reference: https://github.com/apache/paimon/blob/master/paimon-common/src/main/java/org/apache/paim …
=> [flink] FlinkCatalog supports create and drop materialized table
